### ISSUE TITLE
Run `appium-android-driver` tests in `appium-espresso-driver`

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#100]
Instead of reinventing the wheel and re-writing all of the tests, I think we can just import functional tests that we already have in `appium-android-driver` and run them in `appium-espresso-driver`, but skip over the tests that aren't compatible with Espresso (if there are any).

**Comment by jlipps** [comment]
would be a nice way to aim for total compatibility. i like it!
