### ISSUE TITLE
Automation application with Koin as DI

### ISSUE THREAD

**Issue by AlfredAfutu** [appium/appium-espresso-driver#1034]
I keep getting the error "java.lang.IllegalStateException: KoinApplication has not been started" when i run my unit automation tests using appium and espresso driver

To Reproduce

Run "appium start"
Run the unit tests

Expected behavior
The tests should start the application under tests and automate it accordingly

**Comment by AlfredAfutu** [comment]
After moving my koin start code to the attachBaseContext of my Application class, it works. See below:
```
override fun attachBaseContext(base: Context) {
        startKoin {
            androidContext(base)
            modules(appModules)
        }
        super.attachBaseContext(base)
        MultiDex.install(this)
    }
    ```

**Comment by KazuCocoa** [comment]
Thank you for sharing the knowledge
