### ISSUE TITLE
Inject 'INTERNET' permission in AndroidManifest.xml if not present

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#110]
* I used the latest Espresso@master, did a clean install of the `node_modules`, set `forceEspressoRebuild=true`
* It installs the app but can never open and automate the app

https://gist.github.com/dpgraham/084c4785e85736531161e297bd25cb78

**Comment by imurchie** [comment]
Hmm. Works locally for me. Can you delete your gradle stuff (`rm -rf espresso-server/.gradle && rm -rf ~/.gradle`) and try again?

**Comment by dpgraham** [comment]
Should it be re-signing `com.example.android.contactmanager` to `io.appium.espressoserver `

**Comment by imurchie** [comment]
Grade: 4.7 (isn't that specified in the project? so it should be encoded in the branch of the repo?)
SDK tools: 27.0.3 

A gist: https://gist.github.com/imurchie/cffe5629488a82f1239e1ccefe17c240

**Comment by dpgraham** [comment]
I tried with api-demos.apk and now it's working.

@imurchie can you try with `ContactManager.apk`?

**Comment by jlipps** [comment]
I just tried with my own app (https://github.com/cloudgrey-io/the-app) and it seems to work fine.

**Comment by imurchie** [comment]
Turns out you need `INTERNET` permissions. Not sure the Contact Manager will work, since we don't have the source. But I added it to the GPS demo and it worked fine.
```xml
<uses-permission android:name="android.permission.INTERNET" />
```

**Comment by dpgraham** [comment]
I'm going to work on this now.

I think this needs to be an `opt-in` feature. Users should have to set a capability called `injectInternetPermission=true`.

This is so that users don't have their apk's unknowingly tampered with _and_ so that they're aware of the possibility of a permission being set to true and the tests potentially returning false positives.

**Comment by mykola-mokhnach** [comment]
There is a primitive for checking that in appium-adb already called `hasInternetPermissionFromManifest`. I'd simply throw an exception if the corresponding permission is missing

**Comment by dpgraham** [comment]
@mykola-mokhnach Yeah that's what I'll do by default.

Do you not think it's worth the time to a capability that injects it into the manifest? It probably is pretty rare that this permission isn't set.

**Comment by mykola-mokhnach** [comment]
I would say it is an overkill. Lets make it simple
