### ISSUE TITLE
Running different apps in sequence doesn't work

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#124]
Steps to Reproduce
* Run a session in one app
* Run a session in another app
* The second session will keep using the signed debug apk from the first session

The way I was able to work around it was wiping the data on the emulator

**Comment by dpgraham** [comment]
@imurchie and @jlipps do either of you know why this happens? Does it not clean up the debug apk?

**Comment by jlipps** [comment]
i don't know why this would be. when you say "signed debug apk" do you mean the app apk? or the espresso apk? or what?

**Comment by dpgraham** [comment]
The Espresso apk. When the second session is run it has the same package/signature as the original apk that was tested.
