### ISSUE TITLE
Add UiAutomator2 vs. Espresso Document

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#127]
Add a doc to `appium/appium` outlining the differences between UIA2 and Espresso and providing a migration guide.

Some differences are:
1. Espresso uses idling resources which means not needing to wait for UI updates
2. Espresso can access elements that are not on the screen
3. UiAutomator2 is black box and thus can automate multiple apps, Espresso only tests the App-under-test (AUT)

**Comment by KazuCocoa** [comment]
Should we mention about uiselector in https://appium.io/docs/en/writing-running-appium/android/uiautomator-uiselector/ ?

Probably Espresso driver won't support `uiautomator` as `find by`.
https://github.com/appium/appium/issues/6025#issuecomment-407876785

**Comment by dpgraham** [comment]
@kazucocoa yep... it won't support that. That's a thing that needs to be mentioned.

**Comment by dpgraham** [comment]
Added to README
