### ISSUE TITLE
Create re-usable W3C actions spec implementation

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#135]
We'll need to be able to be flexible for future cases where we need to re-implement W3C touch actions in the event that:
a) We have to implement W3C touch actions on some other Java platform
b) A new underlying Android technology is provided by Google and we have to adapt to that

My proposal is that we:
1. Implement the [specification](https://www.w3.org/TR/webdriver/#actions) independently of any underlying technology (Espresso, UiAutomator, etc...) 
2. Implement the spec using an adapter model that lets us interchange implementations
3. Implement the Espresso implementation

**Comment by jlipps** [comment]
big fan of this idea. reusable java modules seems like a great way to not copy/paste stuff around the drivers. i'm not sure if you have this in mind, but we could extend this to the whole of the protocol, similarly to how we have a base-driver in the JS world. we could have a set of BaseDriver java classes, so only the implementation details differ between say uiautomator2 and espresso.

**Comment by mykola-mokhnach** [comment]
It would be interesting to see the actual implementation. I'm wondering if there are really so many common things in different Android automation frameworks that these could be extracted into a common lib.

**Comment by dpgraham** [comment]
@jlipps For this epic I just want to make it work for W3C Touch Actions, but yes I think we're on the same page that my ideal implementation is that we'd decouple it into 1. A Java server that handles routing and dispatching routes to handlers 2. Adapters for Android (or some other possible Java-based Appium implementation) that hook into the handlers without any awareness of HTTP or the specification

**Comment by dpgraham** [comment]
@mykola-mokhnach The main goal with this is that I want to de-couple the implementation of the spec from the actual execution of the native Android events. This is so we can easily unit test spec code and we can troubleshoot issues more easily by being able to distinguish spec issues from native Android issues. I do plan on using your code for the 'adapter' portion of the implementation.
