### ISSUE TITLE
Starting Espresso Server session failed 

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-espresso-driver#208]
I was unable to start a new session and bumped at below error 

https://gist.github.com/saikrishna321/fa515b751d937f3c466671ec704633f9

Appium server : Latest master
Client: 6.1.0

**Comment by dpgraham** [comment]
* Did you clean the `node_modules` and reinstall? (`rm -rf node_modules && npm install`)
* Are you able to share the logcat logs for when the session is being created?
* Did this work with the previous version and then stop working? Or has it ever worked?
* Does anything happen on the device/emulator?

**Comment by imurchie** [comment]
I've made a couple of PRs (in [appium-base-driver](https://github.com/appium/appium-base-driver/pull/249) and [teen_process](https://github.com/appium/node-teen_process/pull/33)) to try to add some visibility to these sorts of situations. With them, hopefully manually trying the command might add something to the debugging.

**Comment by saikrishna321** [comment]
@dpgraham nothing happens when i run this command 

> adb shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner

In Android 8.1.0 nothing happens, just keeps executing.
In Android 5.1.0 it executes both manually and from Appium.

> Did you clean the node_modules and reinstall? (rm -rf node_modules && npm install)
 Yes

> Are you able to share the logcat logs for when the session is being created?
https://gist.github.com/saikrishna321/b2370198899052c0d1aaa226a1f92f81

> Did this work with the previous version and then stop working? Or has it ever worked?
Not sure, haven't tested on 8.1.0 before

> Does anything happen on the device/emulator?
Just installs the APK and io.appium.espressoserver.test APK nothing else.

**Comment by imurchie** [comment]
What happens when you run the command by itself?
```
/Users/shridhk/GitHub/Documents/VodQAAppium/Tools/SDK/platform-tools/adb -P 5037 -s 81c16a94 shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner
```

**Comment by saikrishna321** [comment]
@imurchie nothing happens, just keeps executing.

**Comment by shridharkalagi** [comment]
Yup. Nothing is happening.

**Comment by imurchie** [comment]
Is this a real device, or an emulator?

**Comment by saikrishna321** [comment]
real device

**Comment by shridharkalagi** [comment]
Here is the logcat info
https://gist.github.com/shridharkalagi/bcb713face7d550ff63af7df88e5c83b

**Comment by imurchie** [comment]
Strange. Using my Pixel with 8.1.0 it works fine. The only notable difference is that I have build tools for `28.0.2` installed. Uninstalling it doesn't seem to make a difference, but  ¯\_(ツ)_/¯

**Comment by dpgraham** [comment]
@shridharkalagi Can you try `adb kill-server && adb start-server`? Looks like yours is similar to this: https://github.com/googlesamples/android-testing/issues/89

**Comment by imurchie** [comment]
While running the adb command to start the server, can you try going to `http://0.0.0.0:8080/status`? To see if the server is running but adb is not reporting it?

**Comment by saikrishna321** [comment]
@dpgraham restarting the adb server it works now and i'm able the run the tests 

@imurchie when i run the command now after restarting the adb server

```
adb shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner
```

```
android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Instrument.run(Instrument.java:421)
	at com.android.commands.am.Am.runInstrument(Am.java:187)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:329)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
```

**Comment by saikrishna321** [comment]
@imurchie @dpgraham i bumped at this issue again on the same device, this time even adb kill-server and start-server didn't help. tried removing the espresso apk from device.No luck

**Comment by dpgraham** [comment]
@saikrishna321 Are the logs the same?

**Comment by saikrishna321** [comment]
@dpgraham yes same logs

**Comment by dpgraham** [comment]
@saikrishna321 Can you try setting `forceEspressoRebuild=true` in the caps?

**Comment by saikrishna321** [comment]
@dpgraham i'm unable to test this now as the latest master has broken in session creation for espresso. I have issue raised at server side

https://github.com/appium/appium/issues/11525

**Comment by dpgraham** [comment]
Okay, thanks for letting me know.

**Comment by dpgraham** [comment]
Let me know if this is still an issue.

**Comment by akliuieva** [comment]
Faced the same issue with Espresso appium driver
Appium server - 1.10.0
Java client -7.0.0(tried 6.1.0 - also not working)
Tried :
1) adb kill-server && adb start-server
2) rm -rf node_modules && npm install
3) forceEspressoRebuild=true

Still faced with issue

**Comment by vitalyk** [comment]
Hi guys, I'm facing the same issue.
a fragment - how it fails in the end:
```
[Espresso] Installed Espresso Test Server apk '/var/folders/7d/23_ms4d10fgfrp647061wld00000gn/T/io.appium.espressoserver.test_1.13.0_app.web.app.apk' (pkg: 'io.appium.espressoserver.test')
[debug] [Espresso] Performing cleanup of automation leftovers
[debug] [Espresso] No obsolete sessions have been detected (Error: socket hang up)
[Espresso] Starting Espresso Server v1.13.0 with cmd: adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[debug] [Espresso] Deleting espresso session
```
Can someone please suggest a fix solution? I've tried the steps from above, but no luck.
Thanks ahead for your advice.

**Comment by russtu** [comment]
I have updated the driver to the latest version 2.26.10 and I have made a "gradle wrapper" as my colleague comments and my error is:
Principal error in gradle wrapper command: 
`FAILURE: Build failed with an exception.

* Where:
Build file '/home/.appium/node_modules/appium-espresso-driver/espresso-server/app/build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Failed to create service 'com.android.build.gradle.options.ProjectOptionService_577971f5-275a-419d-b6d7-3ae36b1136ca'.
      > Could not create an instance of type com.android.build.gradle.options.ProjectOptionService.
         > Cannot obtain value from provider of Gradle property 'android.testInstrumentationRunnerArguments.package' at configuration time.
           Use a provider returned by 'forUseAtConfigurationTime()' instead.
`
I tried gradlew clean build command and it gives me this error: 
`> Task :app:testDebugUnitTest

io.appium.espressoserver.EspressoServerRunnerTest > startEspressoServer FAILED
    java.lang.NoClassDefFoundError at EspressoLink.android.kt:71
        Caused by: java.lang.ExceptionInInitializerError at Preconditions.java:2

145 tests completed, 1 failed, 1 skipped

> Task :app:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.
`
