### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.toString()' on a null object reference

### ISSUE THREAD

**Issue by eMTe123** [appium/appium-espresso-driver#222]
## The problem

Hello!

I am trying to use 1.9.0 with "automationName" : "Espresso". I get the error below, using appium inspector 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): N/A using Appium-desktop with Appium 1.9
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Emulator

## Details

I want to launch appium with the mentioned capability set for mye app. The app launches in inspector mode, but crashes with the log added below

## Link to Appium logs

https://gist.github.com/eMTe123/b6e155f2a1fc84eeed524d72a4245c39

## Code To Reproduce Issue [ Good To Have ]
Want to launch appium with capability: "automationName" : "Espresso"
E.G.
{
  "platformName": "android",
  "platformVersion": "9",
  "app": "/home/n639216/apks/app-nrk-feature.apk",
  "deviceName": "Nexus_5X_API_28",
  "appPackage": "no.nrk.mobil.radio.feature",
  "appActivity": "no.nrk.mobil.radio.MainActivity",
  "automationName": "Espresso"
}

**Comment by mykola-mokhnach** [comment]
There might be a problem with activity startup. I've pushed a PR which fixes exception output, but this anyway won't fix the original cause. Try to remove package and activity names so the script can autodetect these and if it still does not work then make sure you can manually start the app using the data above with `adb shell am start` utility.

**Comment by eMTe123** [comment]
Removing package and activity yields the same result. Running 'adb shell am start' with package and activity starts the app up fine.

**Comment by mykola-mokhnach** [comment]
Try the recent beta release it should perform properly

**Comment by dpgraham** [comment]
Closing. Will re-open if problem persists.
