### ISSUE TITLE
1.9.2-beta.2 - Session termination not handled correctly

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-espresso-driver#258]
Logs : https://gist.github.com/saikrishna321/be7657ebe173033bd1b7f64db3ee5768

Comment from @sravanmedarapu

regarding bind failed issue.., it’s because of the server not being closed properly
https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java#L43

will spend sometime over the weekend to implement session handling

and regarding intent.. looks like something going wrong here
https://github.com/appium/appium-espresso-driver/blob/7bd1fd13d6d2d3f6fe23a739057b009cebab7f1b/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.java#L56

**Comment by saikrishna321** [comment]
regarding wrong intent : https://gist.github.com/saikrishna321/262c2e66f305e9dc505a8793234f3b69#file-wrong-intent-handling-L147

Either App package and App activity of the previous session is picked

**Comment by mykola-mokhnach** [comment]
I have an idea about what the problem can be
