### ISSUE TITLE
An element outside display appears when we call find_elemnt

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-espresso-driver#279]
# Steps

1. Scroll up/down to make an element gone
    -e.g.: _Custom_ named element
2. Call `find_element` the element
3. Then, the element appears in the screen
    - This  happens when we call getting attributes method like `displayed?`

# animation gif

![image](https://user-images.githubusercontent.com/5511591/47887666-040fe500-de84-11e8-81a2-ee8ed7f50fd0.png)

---

If users have a logic making sure any elements disappear from a screen or can't find such elements, it should break with this behaviour.

**Comment by mykola-mokhnach** [comment]
I assume this is going to be fixed by https://github.com/appium/appium-espresso-driver/pull/278

**Comment by dpgraham** [comment]
So this behaviour is actually _expected_

When finding elements using `accessibility-id` it makes use of `onData` to try to scroll the element into view if the element isn't on the screen (see https://medium.com/androiddevelopers/adapterviews-and-espresso-f4172aa853cf for reference)

I suppose this could be a problem. So I think we have some options:

1. Leave it as is, and inform users in documents that, when locating an element via `accessibility-id`, it will try to scroll the element into view
2. Take this feature out, but add another endpoint/feature that scrolls elements into view. We could possibly even use the existing `moveTo` feature

So it would be something like: 

```javascript
driver.scrollTo('someAccessibilityId');
```

I definitely want to have this as a feature though. I want users to be able to instantly scroll to off-screen elements.

**Comment by KazuCocoa** [comment]
I see. It sounds reasonable to keep this feature. 👍 
_1_ is probably enough as the 1st release.

One thing is below comment in my description.
> This happens when we call getting attributes method like displayed?

This happens in below case as well.

```ruby
el = driver.find_element :accessibility_id, _Custom_
# scroll down and the _Custom_ has gone
el.displayed? # returns _true_ and the el, which is the _Custom_ element, appears in the screen 
```

Then, returning `false` is proper in this case. Can we return _false_ in this case? (What do you think?)

**Comment by dpgraham** [comment]
I don't think there's a good fix for this. What we'll need in the future is a selector strategy that targets adapter and recycler views.
