### ISSUE TITLE
Make Espresso Server port configurable

### ISSUE THREAD

**Issue by ania-s** [appium/appium-espresso-driver#280]
It looks that the espresso server port is 8080 and it cannot be configured as a part of Appium Desired Capabilities. And if the testing app uses the same port then appium-espresso-driver cannot be used for its testing. 

Can the espresso server port be made configurable?

**Comment by dpgraham** [comment]
That's a good idea. I'll add that to the list of features/fixes

**Comment by dpgraham** [comment]
We should probably also change the default port to something more random so that it's unlikely to clash with another port.

**Comment by saikrishna321** [comment]
@dpgraham @ania-s the port is configurable, you can set the _systemPort_ to unique and thats how i tested the parallel run

https://github.com/appium/appium-espresso-driver/blob/6277faba2883443a7c7bb88385d20571305ba983/lib/driver.js#L144

**Comment by dpgraham** [comment]
Awesome! Well that makes it easy.

I still think we should change the default to something other than 8080 though.

**Comment by saikrishna321** [comment]
@dpgraham should we change to as UIA2 https://github.com/appium/appium-uiautomator2-driver/blob/70c1dacf1d97348d0fa9d4b613692d783488ceb7/lib/driver.js#L24

**Comment by dpgraham** [comment]
Maybe 6791 so those 2 can't clash

**Comment by dpgraham** [comment]
Closed as resolved.
