### ISSUE TITLE
The elements of webview application are not accessible

### ISSUE THREAD

**Issue by ania-s** [appium/appium-espresso-driver#281]
When running automated tests with appium-espresso-driver agains Android webview app no elements of this app are accessible. I can only see the MainWebView element (the whole app), however, anything that is inside (buttons, labels, textfields etc) cannot be accessed.

**Comment by dpgraham** [comment]
Yeah, that's expected. Espresso Server won't have access to WebView's natively. You need to switch context.

**Comment by ania-s** [comment]
> Yeah, that's expected. Espresso Server won't have access to WebView's natively. You need to switch context.

Well if I try to do it I get the following error:

> [debug] [AndroidDriver] Returning process name: 'com.abc.app.dev'
> [debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.abc.app.dev"]
> [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.abc.app.dev"]
> [debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.abc.app.dev'
> [debug] [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'WEBVIEW_com.abc.app.dev' of undefined
> [debug] [MJSONWP]     at EspressoDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:107:32)
> [debug] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [debug] [MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [debug] [MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
> [debug] [MJSONWP]     at new Promise (<anonymous>)
> [debug] [MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
> [debug] [MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
>

**Comment by dpgraham** [comment]
What happens if you try to get the source? Does it return the WebView's HTML?

**Comment by ania-s** [comment]
And if I try to switch to Webview context using webdriver method [context](http://webdriver.io/api/mobile/context.html) I get the following error:

> [debug] [AndroidDriver] Returning process name: 'com.abc.app.dev'
> [debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.abc.app.dev"]
> [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.abc.app.dev"]
> [debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.abc.app.dev'
> [debug] [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'WEBVIEW_com.abc.app.dev' of undefined
> [debug] [MJSONWP]     at EspressoDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:107:32)
> [debug] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [debug] [MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [debug] [MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
> [debug] [MJSONWP]     at new Promise (<anonymous>)
> [debug] [MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
> [debug] [MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
> [debug] [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [debug] [MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
> [debug] [MJSONWP]     at EspressoDriver.callee$0$0 [as startChromedriverProxy] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/context.js:219:30)
> [debug] [MJSONWP]     at EspressoDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:65:16)
> [debug] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [debug] [MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [debug] [MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
> [debug] [MJSONWP]     at new Promise (<anonymous>)
> [debug] [MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
> [debug] [MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
> [debug] [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [debug] [MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
> [debug] [MJSONWP]     at EspressoDriver.callee$0$0 [as switchContext] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/context.js:145:30)
> [debug] [MJSONWP]     at EspressoDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:56:14)
> [debug] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [debug] [MJSONWP]     at <anonymous>
> [info] [HTTP] <-- POST /wd/hub/session/6d81a7ac-420f-4b11-a9bb-0020b8b8a1d8/context 500 94 ms - 236
> [info] [HTTP] 
>

**Comment by dpgraham** [comment]
Thanks @ania-s .... looks like it's a bug with the Espresso driver. I'll test this myself.

**Comment by dpgraham** [comment]
I can reproduce it now. Working on a fix. Thanks for your help @ania-s!
