### ISSUE TITLE
Investigate Espresso web atoms

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#290]
To automate Webviews in Espresso, there's a special library that makes use of Selenium Atoms to perform operations on Webviews.

This could possibly be implemented in the Appium Driver and could even let us automate webviews without needing Chromedriver and without changing context

Acceptance Criteria
* [ ] Determine if it's worth the time to make use of this library
* [ ] If yes, plan how it will be implemented
* [ ] Make implementation issues

**Comment by mykola-mokhnach** [comment]
I'd say the implementation based on web atoms will be the "poor man" one. Chromedriver provides much broader set of features in comparison to raw javascript stuff in atoms.

**Comment by dpgraham** [comment]
Yeah I think you're right @mykola-mokhnach .... we would keep Chromedriver, but we could use this for hybrid apps that are mostly native but may need some occasional, basic WebView manipulation.

**Comment by jlipps** [comment]
This could be interesting, but as @mykola-mokhnach points out, Chromedriver should remain the "real" option. Which makes me wonder whether having two ways of doing this would be unnecessarily complex or confusing for users. I also would want it to use the same context API.

But I would be open to a capability `useSeleniumAtoms` or similar that makes the context API use this instead of the alternative.

What library is it exactly? Or would we copy code from the ios remote debugger project?

**Comment by dpgraham** [comment]
I forgot to provide the link: https://developer.android.com/training/testing/espresso/web

The possible difference between this and using Chromedriver would be that with Espresso Web you could run webview commands in the same context as native whereas Chromedriver would require switching context.

It could look something like this:

```javascript
const webViewEl = driver.findElementById("#myWebView");
const webEl = await webViewEl.findElementByCssSelector(".my-class");
await webEl.click();
```

**Comment by jlipps** [comment]
that still seems confusing to me. what if there is a clash between a web id and an android id? even if using the context api does nothing other than set an internal flag, i think it'd be worth it to maintain the same usage as elsewhere in appium

**Comment by dpgraham** [comment]
So I've thought about this a lot, and I _definitely_ think we should implement this, for a couple of reasons: 
* At Sauce Labs, one of the constant problem that crops up is problems with ChromeDriver version mismatching and we've even had to resort to compiling our own ChomeDriver to support older versions. This would not have such a problem.
* The Espresso Webdriver Atoms use idling resource, so we'd get the same benefit of having the blocking until UI is finished updating that native commands have

The implementation approach should be, like @jlipps said, use the existing context schema, but in this case we would set context like:

`driver.setContext("<web-view-element-id>")`

To implement this, we could do it on the `espresso-server`.....

If it's a webview handler request (possibly use a querystring), we can re-route it to a Web handler

So, `findElement`.... if it's a web find element can re-route to `findElementWeb` and that would just run the `findElement` webdriver atom.

**Comment by jlipps** [comment]
Yeah, I'm cool with that approach.

**Comment by mykola-mokhnach** [comment]
Linking https://developer.android.com/reference/androidx/test/espresso/web/webdriver/package-summary

**Comment by aldochristiaan** [comment]
Hi, just want to ask .. Is there any documentation about this ? Thanks

**Comment by KazuCocoa** [comment]
Only `webAtoms` section in https://github.com/appium/appium/blob/master/docs/en/commands/mobile-command.md so far

**Comment by aldochristiaan** [comment]
Okay, thank you so much @KazuCocoa 👍 
Because it's not displayed here:
http://appium.io/docs/en/commands/mobile-command/

**Comment by aldochristiaan** [comment]
Hello, i want to ask something @dpgraham 
Is there any example for webAtoms assertion ?
e.g : `.check(webMatches(getText(), containsString(MACCHIATO)));`

I tried to use it, but it kept returning `Atom evaluation returned null!`

Passed this on method chain using java :
```
ImmutableMap.of(
        "name", "check",
        "args", ImmutableMap.of(
                   "name", "webMatches",
                   "atom", Arrays.asList(
                                  ImmutableMap.of(
                                        "name", "perform",
                                        "atom", AtomAction.getText.toString()
                                  ),
                                  ImmutableMap.of(
                                         "name", "containsString",
                                         "args", text
                                 )
                     )
           )
 ))
```
