### ISSUE TITLE
Get WebView tests working on Travis

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#291]
Right now, webview tests are commented out. Need to figure out problems with chromedriver.

**Comment by imurchie** [comment]
Our logic uses `chromedriver --version` to fifure out the version. 2.9, however, just starts when passed `--version`, so the whole thing hangs. I guess that logic needs to be fixed. As well as Chromedriver handling of the webview on the device, which seems un-automatable (2.12 ought to work, but fails).

**Comment by imurchie** [comment]
The technical problems with CD install/start should be handled by https://github.com/appium/appium-chromedriver/pull/103. Not sure if this will actually fix the CI environment here.

**Comment by dpgraham** [comment]
@imurchie the CI environment I don't think is the problem.

**Comment by imurchie** [comment]
I can't get, locally, any version of CD to work with the Android version and webview that are available on Travis.

**Comment by dpgraham** [comment]
Oh, so this is an issue that pre-dates the Espresso driver?

**Comment by imurchie** [comment]
It seems to. We don't run any Chrome tests in CI for any of the other Android drivers, I don't think.
