### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke interface method 'int android.widget.Adapter.getCount()' on a null object reference

### ISSUE THREAD

**Issue by nichotined** [appium/appium-espresso-driver#297]
Hi, I found `An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke interface method 'int android.widget.Adapter.getCount()' on a null object reference while sending a get source method.`
Somehow after changing to "this screen", it will throw this error.

### Environment

- AVD android 9
- appium 1.9.2 beta 2
- Capabilities
```
&{CAPS}     platformName=Android
...                 platformVersion=9.0
...                 udid=emulator-5554
...                 deviceName=Emulator
...                 appActivity=com.presentation.feature.LifeSplashActivity
...                 autoGrantPermissions=True
...                 automationName=Espresso
```

### Link to appium log
[Click here](https://gist.github.com/nichotined/dc83a1e4ae2f2673e7ec43b6fb22e062)

**Comment by mykola-mokhnach** [comment]
This has been fixed by https://github.com/appium/appium-espresso-driver/pull/293

**Comment by nichotined** [comment]
@mykola-mokhnach How do I get that update?

**Comment by mykola-mokhnach** [comment]
Wait until it is published or built the server from sources

**Comment by mykola-mokhnach** [comment]
@saikrishna321 yes it is

**Comment by dpgraham** [comment]
Closing this. If this is still a problem, I'll re-open.
