### ISSUE TITLE
Permission denial exception starting instrumentation

### ISSUE THREAD

**Issue by VinayakaMayura** [appium/appium-espresso-driver#302]
Permission denial exception while starting instrumentation

Appium: latest beta from source
Latest Java client from latest commit
Logs:  https://gist.github.com/VinayakaMayura/1acfd43dfbcadee9fe39134a6eecf633
Same even after setting `"forceEspressoRebuild" : true,`

Also same on Android API 7, 8 and 9 devices.

Executing command from terminal resulted the same:
```
adb shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner

java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner} from pid=27963, uid=27963 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.XXXXXX.YYYYYYYY
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner} from pid=27963, uid=27963 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.XXXXX.YYYYYYYY
INSTRUMENTATION_STATUS_CODE: -1
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.startInstrumentation(ActivityManagerNative.java:4546)
	at com.android.commands.am.Am.runInstrument(Am.java:889)
	at com.android.commands.am.Am.onRun(Am.java:400)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:121)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
```

**Comment by VinayakaMayura** [comment]
@mykola-mokhnach please suggest

**Comment by KazuCocoa** [comment]
What happens when you remove `noSign`?

**Comment by SrinivasanTarget** [comment]
@KazuCocoa No luck. Issue remains as is after removing `noSign` and upgrading to `1.2.0` espresso driver. @mykola-mokhnach FYI

**Comment by nichotined** [comment]
Try to uninstall the app and espresso from the device

**Comment by SrinivasanTarget** [comment]
@dpgraham Sure will share it tomorrow morning

**Comment by VinayakaMayura** [comment]
Logs: https://gist.github.com/VinayakaMayura/0fea681c57422a0f97d65191e9375ddf#file-espresso-log

@dpgraham

**Comment by saikrishna321** [comment]
@VinayakaMayura i don't see any errors in the logs now

**Comment by VinayakaMayura** [comment]
Not getting the permission denial exception now. 

Noticing session creation exception when noSign is set to false

**Comment by mykola-mokhnach** [comment]
Try to delete the espresso server package manually from the device first

**Comment by VinayakaMayura** [comment]
@mykola-mokhnach  tried by clearing espresso server manually but no luck.

Logs after clearing espresso server manually each time

noSign set to true
https://gist.github.com/VinayakaMayura/81dff2ac4fbb7742b9a0ee3878369abc

noSign set to false
https://gist.github.com/VinayakaMayura/a00745c42c5305b402462c2783b67f1a

**Comment by mykola-mokhnach** [comment]
The second log is perfectly fine. No errors on server side

**Comment by VinayakaMayura** [comment]
@mykola-mokhnach  though there are no exceptions in the log, app gets installed and launches but no actions performed for both the cases of noSign

**Comment by VinayakaMayura** [comment]
Thanks guys, looks like client side issue. Will check it form our side.
