### ISSUE TITLE
findElementsFromElement and findElementFromElement always throws ProxyRequestError

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium-espresso-driver#311]
findElementsFromElement and findElementFromElement always throws ProxyRequestError

Appium Server: Latest source
Java client: Latest version
Logs [here](https://gist.github.com/SrinivasanTarget/9c786bbfc6c3eb83eec924aa7d010ee8#file-findelementsfromelement-L1961)

@mykola-mokhnach @dpgraham ping

**Comment by nichotined** [comment]
Try look at the source and find your elemet first.

**Comment by saikrishna321** [comment]
@SrinivasanTarget does this happen on specific component ?

**Comment by SrinivasanTarget** [comment]
@nichotined Source is fine... Its not problem with source and seems like a element detection issue.

@saikrishna321 Its not w.r.t specific component.

**Comment by dpgraham** [comment]
Try again with `appium@1.10.0-beta.5`

**Comment by SrinivasanTarget** [comment]
@dpgraham @mykola-mokhnach Issue persists still. Updated logs [here](https://gist.github.com/SrinivasanTarget/8c1c9563b29b27a6ea0599f47ae7199c#file-findelementfromelement-L711)

**Comment by mykola-mokhnach** [comment]
Are you sure the element exists on the page? Can you also attach the page source?

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach I have updated the source [here](https://gist.github.com/SrinivasanTarget/8c1c9563b29b27a6ea0599f47ae7199c#gistcomment-2768783)

**Comment by SrinivasanTarget** [comment]
i tried findElementFromElement at couple of places in different different screens but i see response is always same. It works fine in UIA2 mode.

**Comment by mykola-mokhnach** [comment]
What is the actual search request? What are the locators of the root and descendant elements?
