### ISSUE TITLE
ECONNRESET after restarting the app

### ISSUE THREAD

**Issue by ania-s** [appium/appium-espresso-driver#314]
It looks that I cannot test anything after I restart the android app as I get the following error (tested on real android device Galaxy Tab S2):

> An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

The full log:

> [debug] [35m[MJSONWP][39m Calling AppiumDriver.closeApp() with args: ["86e83ba8-9c45-4b3c-b40a-1ca957cda263"]
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell am force-stop com.abc.app.dev'
[debug] [35m[Espresso][39m [Instrumentation][STDOUT] io.appium.espressoserver.EspressoServerRunnerTest:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Espresso][39m [Instrumentation][STDOUT] INSTRUMENTATION_CODE: 0
[35m[Espresso][39m Instrumentation process exited with code 0 from signal null
[debug] [35m[AndroidDriver][39m Stopping chromedriver for context WEBVIEW_com.abc.app.dev
[debug] [35m[Chromedriver][39m Changed state to 'stopping'
[debug] [35m[JSONWP Proxy][39m Proxying [DELETE /] to [DELETE http://127.0.0.1:8002/wd/hub/session/a9fd30ed139e101f71e22c2c674de4e7] with no body
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"a9fd30ed139e101f71e22c2c674de4e7\",\"status\":0,\"value\":null}"
[debug] [35m[Chromedriver][39m Changed state to 'stopped'
[debug] [35m[MJSONWP][39m Responding to client with driver.closeApp() result: null
[35m[HTTP][39m [37m<-- POST /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/appium/app/close [39m[32m200[39m [90m825 ms - 76[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/appium/app/launch[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.launchApp() with args: ["86e83ba8-9c45-4b3c-b40a-1ca957cda263"]
[debug] [35m[ADB][39m Checking app cert for /Users/user/abc/platform/runtime-android/app/build/outputs/apk/dev/debug/app-dev-debug.apk
[debug] [35m[ADB][39m Starting '/Users/szarek/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Users/user/abc/platform/runtime-android/app/build/outputs/apk/dev/debug/app-dev-debug.apk"]'
[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [35m[ADB][39m WARNING: META-INF/android.arch.core_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/android.arch.lifecycle_livedata-core.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/android.arch.lifecycle_livedata.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/android.arch.lifecycle_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/android.arch.lifecycle_viewmodel.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.appcompat_appcompat.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.coordinatorlayout_coordinatorlayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.core_core.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.cursoradapter_cursoradapter.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.customview_customview.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.documentfile_documentfile.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.drawerlayout_drawerlayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.fragment_fragment.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.interpolator_interpolator.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.legacy_legacy-support-core-ui.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.legacy_legacy-support-core-utils.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.loader_loader.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.print_print.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.slidingpanelayout_slidingpanelayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.vectordrawable_vectordrawable-animated.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.vectordrawable_vectordrawable.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.versionedparcelable_versionedparcelable.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/androidx.viewpager_viewpager.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/proguard/androidx-annotations.pro not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/Users/user/abc/platform/runtime-android/app/build/outputs/apk/dev/debug/app-dev-debug.apk' is already signed.
[debug] [35m[ADB][39m Getting install status for com.abc.app.dev
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell pm list packages com.abc.app.dev'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting install status for com.abc.app.dev
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell pm list packages com.abc.app.dev'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'com.abc.app.dev'
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell dumpsys package com.abc.app.dev'
[debug] [35m[ADB][39m The installed 'com.abc.app.dev' package does not require upgrade ('1.0.0' >= '1.0.0')
[35m[AndroidDriver][39m Performing fast reset on 'com.abc.app.dev'
[debug] [35m[ADB][39m Getting install status for com.abc.app.dev
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell pm list packages com.abc.app.dev'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell am force-stop com.abc.app.dev'
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell pm clear com.abc.app.dev'
[debug] [35m[AndroidDriver][39m Performed fast reset on the installed 'com.abc.app.dev' application (stop and clear)
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell ls /data/local/tmp/espresso.apppackage'
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell cat /data/local/tmp/espresso.apppackage'
[debug] [35m[Espresso][39m The previous target application package was 'com.abc.app.dev'. The current package is 'com.abc.app.dev'
[debug] [35m[ADB][39m Checking app cert for /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.2.3_com.abc.app.dev.apk
[debug] [35m[ADB][39m Starting '/Users/szarek/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.2.3_com.abc.app.dev.apk"]'
[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [35m[ADB][39m WARNING: META-INF/nanohttpd/default-mimetypes.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/nanohttpd/mimetypes.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/services/com.google.protobuf.GeneratedExtensionRegistryLoader not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/services/org.xmlpull.v1.XmlPullParserFactory not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.2.3_com.abc.app.dev.apk' is already signed.
[debug] [35m[ADB][39m Getting install status for io.appium.espressoserver.test
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell pm list packages io.appium.espressoserver.test'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.espressoserver.test'
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell dumpsys package io.appium.espressoserver.test'
[debug] [35m[ADB][39m The installed 'io.appium.espressoserver.test' package does not require upgrade ('1.0.0' >= '1.0.0')
[35m[Espresso][39m Installed Espresso Test Server apk '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.2.3_com.abc.app.dev.apk' (pkg: 'io.appium.espressoserver.test')
[debug] [35m[ADB][39m Device API level: 24
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell am start -W -n com.abc.app.dev/com.abc.app.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [35m[MJSONWP][39m Responding to client with driver.launchApp() result: null
[35m[HTTP][39m [37m<-- POST /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/appium/app/launch [39m[32m200[39m [90m7227 ms - 76[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/context[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.getCurrentContext() with args: ["86e83ba8-9c45-4b3c-b40a-1ca957cda263"]
[debug] [35m[MJSONWP][39m Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[35m[HTTP][39m [37m<-- GET /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/context [39m[32m200[39m [90m3 ms - 84[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/contexts[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.getContexts() with args: ["86e83ba8-9c45-4b3c-b40a-1ca957cda263"]
[debug] [35m[AndroidDriver][39m Getting a list of available webviews
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell cat /proc/net/unix'
[debug] [35m[AndroidDriver][39m WEBVIEW_23202 mapped to pid 23202
[debug] [35m[AndroidDriver][39m Getting process name for webview
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell ps'
[debug] [35m[AndroidDriver][39m Parsed pid: '23202' pkg: 'com.abc.app.dev' from
[debug] [35m[AndroidDriver][39m     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [35m[AndroidDriver][39m     u0_a224   23202 593   2350968 209152 SyS_epoll_ 0000000000 S com.abc.app.dev
[debug] [35m[AndroidDriver][39m Returning process name: 'com.abc.app.dev'
[debug] [35m[AndroidDriver][39m Found webviews: ["WEBVIEW_com.abc.app.dev"]
[debug] [35m[AndroidDriver][39m Available contexts: ["NATIVE_APP","WEBVIEW_com.abc.app.dev"]
[debug] [35m[MJSONWP][39m Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com.abc.app.dev"]
[35m[HTTP][39m [37m<-- GET /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/contexts [39m[32m200[39m [90m205 ms - 118[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/element[39m
[35m[HTTP][39m [90m{"using":"xpath","value":"//*[@data-test-id='LoginPage_testId']"}[39m
[35m[MJSONWP][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Matched '/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/element' to command name 'findElement'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/element] to [POST http://localhost:8301/session/554f8e8e-c657-47fb-9d3c-35c180fcf608/element] with body: {"using":"xpath","value":"//*[@data-test-id='LoginPage_testId']"}
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
[debug] [35m[MJSONWP][39m     at doJwpProxy$ (/Users/user/abc/test/node_modules/appium-base-driver/lib/protocol/protocol.js:504:13)
[debug] [35m[MJSONWP][39m     at tryCatch (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[35m[HTTP][39m [37m<-- POST /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/element [39m[31m500[39m [90m19 ms - 281[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/screenshot[39m
[35m[HTTP][39m [90m{}[39m
[35m[MJSONWP][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Matched '/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/screenshot' to command name 'getScreenshot'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/screenshot] to [GET http://localhost:8301/session/554f8e8e-c657-47fb-9d3c-35c180fcf608/screenshot] with body: {}
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
[debug] [35m[MJSONWP][39m     at doJwpProxy$ (/Users/user/abc/test/node_modules/appium-base-driver/lib/protocol/protocol.js:504:13)
[debug] [35m[MJSONWP][39m     at tryCatch (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke (/Users/user/abc/test/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[35m[HTTP][39m [37m<-- GET /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263/screenshot [39m[31m500[39m [90m6 ms - 281[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.deleteSession() with args: ["86e83ba8-9c45-4b3c-b40a-1ca957cda263"]
[debug] [35m[BaseDriver][39m Event 'quitSessionRequested' logged at 1543231166264 (12:19:26 GMT+0100 (Central European Standard Time))
[35m[Appium][39m Removing session 86e83ba8-9c45-4b3c-b40a-1ca957cda263 from our master session list
[debug] [35m[Espresso][39m Deleting espresso session
[debug] [35m[Espresso][39m Deleting Espresso server session
[debug] [35m[JSONWP Proxy][39m Matched '/' to command name 'deleteSession'
[debug] [35m[JSONWP Proxy][39m Proxying [DELETE /] to [DELETE http://localhost:8301/session/554f8e8e-c657-47fb-9d3c-35c180fcf608] with no body
[35m[Espresso][39m Did not get confirmation Espresso deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 shell am force-stop com.abc.app.dev'
[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Device API level: 24
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8301 
[debug] [35m[ADB][39m Running '/Users/szarek/Library/Android/sdk/platform-tools/adb -P 5037 -s d0ac6cf4 forward --remove tcp\:8301'
[debug] [35m[BaseDriver][39m Event 'quitSessionFinished' logged at 1543231167014 (12:19:27 GMT+0100 (Central European Standard Time))
[debug] [35m[MJSONWP][39m Received response: null
[debug] [35m[MJSONWP][39m But deleting session, so not returning
[debug] [35m[MJSONWP][39m Responding to client with driver.deleteSession() result: null
[35m[HTTP][39m [37m<-- DELETE /wd/hub/session/86e83ba8-9c45-4b3c-b40a-1ca957cda263 [39m[32m200[39m [90m752 ms - 76[39m
[35m[HTTP][39m [90m[39m

**Comment by ania-s** [comment]
> This is intermittent, have you tried to restart appium server?

Yes, I have. But the problem is that it happens every single time I restart the app. So it doesn't look like it's intermittent.

**Comment by nichotined** [comment]
@ania-s Could you give the environment details?

**Comment by ania-s** [comment]
@nichotined 
ADB: 1.0.40
Samsung Galaxy Tab S2 (Android version 7.0)
Appium: 1.10.0-beta.4
Appium-chromedriver: 4.9.0
Mac HighOS Sierra (10.13.6)

Anything else I should include?
I will try it with a different device as well, I just need to get it.

**Comment by mykola-mokhnach** [comment]
> Yes, I have. But the problem is that it happens every single time I restart the app. So it doesn't look like it's intermittent.

I would say this behaviour is expected. It is necessary to quit the driver and start it again if the app is restarted.

**Comment by ania-s** [comment]
> > Yes, I have. But the problem is that it happens every single time I restart the app. So it doesn't look like it's intermittent.
> 
> I would say this behaviour is expected. It is necessary to quit the driver and start it again if the app is restarted.

If I start the automation with Appium I am able to restart the app with the UiAutomator and continue testing without any manual commands. Testing on iOS with Appium allows this as well. So if it's expected with espresso-driver shouldn't it be done automatically as a part of 'restart' command? Or how can I do it if I don't use espresso-driver directly but it's used by Appium?

**Comment by mykola-mokhnach** [comment]
Both UIA and XCUITest use separate servers while Espresso runs on top of application package and is terminated as soon as this package is terminated. Please consider deeper framework architecture investigation to know more about it.

**Comment by ania-s** [comment]
> Both UIA and XCUITest use separate servers while Espresso runs on top of application package and is terminated as soon as this package is terminated. Please consider deeper framework architecture investigation to know more about it.

Ok thanks for the explanation. I will try to find some more time to check the espresso-driver, however, a more detailed documentation would be helpful.
Anyway it's clearer now, however, even if the espresso-driver is terminated as soon as the package is terminated I would expect it's started the moment the app is started again. Especially if it was started automatically on the first run. If I start the driver manually I would expect I need to do it again.

**Comment by jlipps** [comment]
@mykola-mokhnach @dpgraham if the espresso server dies in a non-recoverable way after the app itself quits, should we disable some of the app management commands for this driver so that users cannot shoot themselves in the foot with them?

**Comment by mykola-mokhnach** [comment]
Nah, lets be democratic %)

**Comment by ania-s** [comment]
Any news about this one? I mean even if the driver is not brought up again automatically after the app is restarted there should be a way to handle it manually. Is there a way to do it? If the driver is killed and there is no way to restart it it's really bad as many tests require that app is restarted.

**Comment by leandromercado** [comment]
Is there any update on this or a workaround?

**Comment by rajdeepv** [comment]
@ania-s What client are you using? Are you restarting app using appium or some other way? If you are killing app and restarting using some other mechanism other than appium client, then it will not work because instrumentation will not be started

**Comment by ania-s** [comment]
@rajdeepv I use Android tablets, few different ones(e.g. Galaxy Tab S3, Lenovo TB-X304F). And yes I restart the app using appium.

**Comment by rajdeepv** [comment]
@ania-s I tried with the ruby client and driver.restart is working fine, and I am able to drive app fine post that. What language are you using?

**Comment by mvrazi** [comment]
Hi. Is anyone working on this case? 
An issue occurs using Java.

**Comment by dpgraham** [comment]
@mvrazi is this still happening with the latest Appium? (1.12.0)

**Comment by mvrazi** [comment]
@dpgraham yes.

I'm attaching logs after calling "appiumDriver.resetApp" method using latest Appium. (1.12.0)

[resetApp_ECONNRESET.log](https://www.dropbox.com/s/4m5zwmpil9kuv1k/resetApp_ECONNRESET.log?dl=0)

**Comment by TomBAMU** [comment]
Is there any news on this? Some of our testcases require to call a "RESET" but the session will crash as @mykola-mokhnach stated.
Would be awesome if we could use Espresso for these cases.

**Comment by TomBAMU** [comment]
Seems like #451 fixes the problem for us! 👍

**Comment by dpgraham** [comment]
Closing as fixed then. Thank you @tombamu
