### ISSUE TITLE
Implement GeneralSwipeAction and GeneralClickAction

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#328]
We have the Actions API already but I see no reason not to expose [GeneralSwipeAction](https://developer.android.com/reference/androidx/test/espresso/action/GeneralSwipeAction) and [GeneralClickAction](https://developer.android.com/reference/androidx/test/espresso/action/GeneralClickAction) to the Espresso Driver.

**Comment by jlipps** [comment]
yeah, if we can use an interface as near as possible to mobile: scroll and mobile: swipe that already exist for ios, that would be great.

**Comment by dpgraham** [comment]
Yeah, we already have `mobile: swipe` for Espresso, we'll just add to it.
