### ISSUE TITLE
Driving out of app areas

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#359]
There are cases where we have to drive out of app areas. Example:
AppUnderTest (has an upload photo button which opens Android Gallery)=> Select photos => Back to AppUnderTest
AppUnderTest => Open GooglePlay payment flow => Pay using GooglePlay => Back to AppUnderTest

espresso-driver already has InteractionHelper with UiDevice and therefore there is a possibility of driving out of app areas. It can possibly be a simple mobile command to which we give uiautomator2 script to execute (similar to https://github.com/appium/appium-uiautomator2-server/blob/ce4b766cf702e9d0b8b2304b06a8fd00aaff8fd6/app/src/main/java/io/appium/uiautomator2/utils/UiAutomatorParser.java)

**Comment by dpgraham** [comment]
Yeah this is a limitation of Espresso....

I think what we should be doing is merging our UiAutomator2 driver into Espresso and having the ability to change native contexts.

**Comment by rajdeepv** [comment]
It definitely makes sense to merge both given they have mutually exclusive powers. Is it a plan in near future?

**Comment by rajdeepv** [comment]
@dpgraham as a stop-gap, do you think its a good idea to add a mobile command which can evaluate a uiautomator2 script to workaround this problem? I can try doing that

**Comment by dpgraham** [comment]
@rajdeepv Yeah if you wanted to work on that, I'm fine with that.

**Comment by KazuCocoa** [comment]
Lovely. > https://github.com/appium/appium-espresso-driver/issues/359#issuecomment-453548834
I also get feedback about it by friends of mine, but I have no time to work for it hard so far...

**Comment by rajdeepv** [comment]
@dpgraham @KazuCocoa, What I meant was not a fully fledged script parser, but just a workaround which helps me in very rare cases when I want to click or get the text/contentDescription etc from out of app areas. I already use the simple workaround from [my fork](https://github.com/rajdeepv/appium-espresso-driver/tree/uiautomator) for my personal projects. Not sure if it is good enough for upstream.

**Comment by mykola-mokhnach** [comment]
@rajdeepv Create a PR. We'll be happy to review as always.
