### ISSUE TITLE
Kotlin?

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#368]
Kotlin

Yay or nay?

**Comment by mykola-mokhnach** [comment]
We can start rewriting some parts step by step

**Comment by mykola-mokhnach** [comment]
...until everything will be in Kotlin

**Comment by dpgraham** [comment]
@mykola-mokhnach I was thinking the same thing. It's helpful that Kotlin is interoperable with Java.

**Comment by jlipps** [comment]
If Google is recommending Android devs move to Kotlin, I think we should as well, bit by bit.
