### ISSUE TITLE
"-android viewmatcher" selector strategy

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#394]
We have the `-android datamtacher` selector strategy (see https://github.com/appium/appium-espresso-driver/pull/386)

We should also have a `-android viewmatcher` selector strategy so that we have all Espresso view-finding strategies covered.

**Comment by o-x-y-g-e-n** [comment]
@dpgraham  I would like to take this opportunity to add the support for view matcher.

**Comment by jlipps** [comment]
thanks @o-x-y-g-e-n, let us know if you need any help; it should be pretty straightforward hopefully to base your work off the datamatcher work.

**Comment by o-x-y-g-e-n** [comment]
@jlipps Yes, I got a lot of reference from the DataMatcher. For View Matcher i am stuck at one place.

for OnView(<ViewMatcher>), now ViewMatcher can be a lot of nested ViewMatchers.
eg. 

for android.support.test.espresso.matcher.ViewMatchers.withClassName it takes an argument of Matcher<String>. Hence its nested Matchers.

Let me explain you with an example. 

`{
	"using":"-android viewmatcher",
	"value":"{\"name\":\"withResourceName\",\"args\":\"io.appium.android.apis:id/text\",\"class\":\"androidx.test.espresso.matcher.ViewMatchers\"}"
}`
The above code concludes to `onView(withResourceName("io.appium.android.apis:id/text"))`

But what if i want to do something like `onView(ViewMatchers.withClassName(is("android.widget.TextView")))` which is nested by an espresso Matcher & Hamcrest Matcher.

is there any support for resolving nested Matchers in our code? If not, let me know if we have any plans to implement it.




I hope I am able to explain the problem properly.

Thanks.

**Comment by KazuCocoa** [comment]
How about like backdoor? (rough idea though)

https://github.com/appium/appium-espresso-driver/blob/db2eb34c7c2ce5a05e93cca129f170941919d75e/lib/commands/general.js#L181-L200

so, for example...:

```
value: [
    {name:'withClassName'
     args: [
          {name: 'is', args: 'android.widget.TextView'}
     ]
    },
]
```

**Comment by o-x-y-g-e-n** [comment]
@jlipps @dpgraham @KazuCocoa   Can we make something like `"using":"-android viewmatcher",
	"value":"{\"name\":[\"withResourceName\",\"containsString\"],\"args\":\"res1\",\"class\":[\"androidx.test.espresso.matcher.ViewMatchers\",\"org.hamcrest.Matchers\"]}"`

which will lead to `onView(withResourceName(containsString('res')))`

We can pass multiple name (i.e strategies) and respective classes. I have already done the implementation for the above mentioned approach. Is this a right approach to follow.

**Comment by jlipps** [comment]
I’m not familiar enough with the underlying API to know whether this is a good JSONification of it; @dpgraham, any thoughts?

**Comment by dpgraham** [comment]
@o-x-y-g-e-n do you have a branch I can look at? The `-view` tag should be very similar to how `-data` tag works.
