### ISSUE TITLE
Will we support open_notification?

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-espresso-driver#440]
Because https://github.com/appium/appium/blob/16f545c37d730fca431fcd2cb9767221312738dd/commands-yml/commands/device/system/open-notifications.yml#L47 is true.
If we have no plan yet, I would make it `false`.

https://github.com/appium/appium-uiautomator2-server/search?q=OpenNotification&unscoped_q=OpenNotification

cc @dpgraham

**Comment by mykola-mokhnach** [comment]
I think it makes not much sense for espresso, since it cannot access elements outside the application sandbox and the notifications drawer is exactly an example of such element

**Comment by KazuCocoa** [comment]
Exactly, I agree with you

**Comment by KazuCocoa** [comment]
I've created a PR to make this feature false so far.
(close this issue as well)
