### ISSUE TITLE
How to  compile appium.espressoserver.test with same app signature?

### ISSUE THREAD

**Issue by Siddh010** [appium/appium-espresso-driver#469]
I got below error message  while trying  with espresso as automation Name.

Please someone let now where can we  find io.appium.espressoserver.test and what are the steps require to compile with same signature as app?.

[Espresso] [Instrumentation] [STDERR] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=28449, uid=28449 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.participantmobileapp
[Espresso] Deleting espresso session
[ADB] Running '/Users/gwgmobilelab/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH930d97c0eae shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'

Appium Server Log :- https://gist.github.com/ad19b7d4b1736df3f8272d7a5c5bc69c.git

**Comment by mykola-mokhnach** [comment]
> [ADB] The version code of the installed 'com.participantmobileapp' is greater than the application version code (63 > 56)

Uninstall the newer version of the app manually from the device, so the resigned one can be installed

**Comment by Siddh010** [comment]
Thank you @mykola-mokhnach, After update my App I was able to use Espresso as automation Name.
Going forward do we need to have same app version in local  folder and devices?

I was not facing this issue with UIAutomator2. 
We used to  get app update  in Crashlytics app and install directly in devices without saving newly update app in local test folder.

**Comment by mykola-mokhnach** [comment]
By default the algorithm always verifies if the version of the installed app is newer or the same in comparison to the version of the app which is going to be installed. You can cancel this by setting `fullReset` cap to true. That guarantees the application under test is always removed from the device before session startup.

**Comment by jlipps** [comment]
If you don't want everything that comes along with `fullReset`, you can also use `uninstallOtherPackages` and include your app package. that will cause your app to always be uninstalled regardless of version.

**Comment by Siddh010** [comment]
Just a thought , I dont want to remove the app which have greater version than the application version code (eg her 63>56) , Then I should be able to resigned. 
Which is not allowing now with Espresso automation.
With FullReset and uninstallOtherPackages  App is getting remove from devices and installing older version from path mention in capabilities.
