### ISSUE TITLE
Backdoor couldn't find methods on target : application / activity if the code written in Kotlin

### ISSUE THREAD

**Issue by aldochristiaan** [appium/appium-espresso-driver#470]
So I have 2 android application written in Kotlin and Java ..

I tried to call public method on my Java Android Application both inside activity and application. It worked!

```
ImmutableMap<String, Object> scriptArgs = ImmutableMap.of(
                "target", "application",
                "methods", Arrays.asList(ImmutableMap.of(
                        "name", "createToast",
                        "args", Arrays.asList(ImmutableMap.of(
                                "value", "Hello",
                                "type", "String"
                        ))
                ))
        );

androidDriver.executeScript("mobile: backdoor", scriptArgs);
```

But when i want to try it on Kotlin Android Application, somehow espresso couldn't find any public methods inside activity nor application.
So I tried to use companion object and moved the function inside and marked it with @JvmStatic annotation.

```
ImmutableMap<String, Object> scriptArgs = ImmutableMap.of(
                "target", "application",
                "methods", Arrays.asList(ImmutableMap.of(
                        "name", "com.xxx.xxxxAplication.Companion.createToast",
                        "args", Arrays.asList(ImmutableMap.of(
                                "value", "Hello",
                                "type", "String"
                        ))
                ))
        );

androidDriver.executeScript("mobile: backdoor", scriptArgs);
```

Is there anything that i can do to get the list of methods inside Java Code / Kotlin Code with backdoor ? Just for debugging purpose.

And is there any solution for this ?

Thank you !

**Comment by KazuCocoa** [comment]
How about _show Kotlin bytecode_ and decompile them to Java on AndroidStudo?

**Comment by aldochristiaan** [comment]
> How about _show Kotlin bytecode_ and decompile them to Java on AndroidStudo?

I tried and it became :
`public final void methodName()`

So, what's next ?

**Comment by dpgraham** [comment]
@rajdeepv do you have any ideas?

**Comment by aldochristiaan** [comment]
Hey guys @dpgraham @rajdeepv @KazuCocoa ..
I found out that we have to put `open` in front of the methods 😁 

`open fun methodName()` will be decompiled into `public void methodName()`

Case closed! Thanks @KazuCocoa for pointing out kotlin bytecode ..
Maybe we have to add documentation about this on appium mobile native command especially for kotlin app 🥇

**Comment by KazuCocoa** [comment]
Thanks!
I took a glance at the code and found `setAccessible(true);`. ah.. final modifier affected.
Will add the kotlin case in doc.

**Comment by aldochristiaan** [comment]
Hello @KazuCocoa, sorry to open this issue again.
I found out that methods are missing in `Activity`, but it worked on `Application` target.

**Comment by KazuCocoa** [comment]
thanks, interesting.
Were there any differences in decoded Java code level?

**Comment by aldochristiaan** [comment]
There is no difference between decoded Java code ..

I have 2 kotlin application, the weird thing is backdoor does work in one application 😭 and the other doesn't.

**Comment by aldochristiaan** [comment]
> thanks, interesting.
> Were there any differences in decoded Java code level?

Hey, I found the root cause of this !!! 😆 
The problem is proguard! OMG ..
In case espresso can't find the methods in activity, make sure to setup the proguard to keep methods used for testing ..
