### ISSUE TITLE
Unable to find the object using espresso driver (view and data matcher tag)

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [appium/appium-espresso-driver#476]
appium Version : 1.1.13
node version: 6.9.0
appium-espresso-driver : 6.9.0

The same resource id is working as expected for UIAutomator2. It is not working when i change the automation name to espresso.

**When using findElementByAndroidDataMatcher**
https://gist.github.com/ramkumary/bdc7c8b8c5059a4631244159594131be

**When using findElementByAndroidViewTag**
https://gist.github.com/ramkumary/9432dd8f963bd02102db629837577043

**Comment by mykola-mokhnach** [comment]
> 15:22:27:859 [HTTP] <-- GET /wd/hub/session/38b08746-0cd2-496c-a8ad-a6b1b0ef5337 200 3 ms - 1130 2019-08-11 15:22:27:859 [HTTP] 2019-08-11 15:22:32:026 [HTTP] --> POST /wd/hub/session/38b08746-0cd2-496c-a8ad-a6b1b0ef5337/element 2019-08-11 15:22:32:027 [HTTP] {"using":"-android datamatcher","value":"{'name':'withId','args':'in.redbus.android:id/selected_country_wrapper'}"}

The value does argument not  look like a valid JSON

**Comment by ramkumary** [comment]
{
	"name": "withId",
	"args": "in.redbus.android:id/selected_country_wrapper"
}

Is this correct JSON format?

**Comment by priyankshah217** [comment]
@ramkumary  you can use below tag like, It will work only on static view like lables and texts,

```
private val userNameTextBox = MobileBy.AndroidViewTag("username")
private val passwordTextBox = MobileBy.AndroidViewTag("password")
```

For data matcher which is works only on adapter view
`private val nativeViewButtonsScreen = MobileBy.androidDataMatcher("{name:'hasEntry',args:['title','chainedView']}")
`

**Comment by ramkumary** [comment]
Code used to build the json is

`JSON.createObjectBuilder().add("name","withId").add("args","in.redbus.android:id/selected_country_wrapper").build.toString();`

**Comment by ramkumary** [comment]
priyankshah217 - Thanks. How do I use resource id with espresso driver?

**Comment by mykola-mokhnach** [comment]
What I can observe in the log is the string, which cannot be coerced to an object. JSON standard required keys and values to use double quotes rather than single quotes

**Comment by mykola-mokhnach** [comment]
Linked https://github.com/appium/appium-espresso-driver/issues/445

**Comment by ramkumary** [comment]
Even with double code seems not working.
`35m[HTTP][39m [90m{"using":"-android viewtag","value":"{\"name\":\"withId\",\"args\":\"in.redbus.android:id/selected_country_wrapper\"}"}[39m`

**Comment by mykola-mokhnach** [comment]
> Even with double code seems not working.
> 35m[HTTP]�[39m �[90m{"using":"-android viewtag","value":"{\"name\":\"withId\",\"args\":\"in.redbus.android:id/selected_country_wrapper\"}"}�[39m

the actual value should be of datamatcher type, it does not look like a tag name
