### ISSUE TITLE
Espresso driver was not able to locate elements, which used to work with UIAutomator-2

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium-espresso-driver#477]
I found an issue while locating an element using an espresso driver, The same locator strategy was working fine with UIAutoimator-2, but it was failing while using espresso driver.

**EspressoDriver:**
https://gist.github.com/priyankshah217/de4a9cf19344e82ac0dd7b135f06a2f5

**UiAutomator-2 Driver:**
https://gist.github.com/priyankshah217/20663116362a06cbac625e2c1843eb56

**Appium Version**
1.13.0

**Java-client Version**
7.1.0

**Code:**
https://github.com/priyankshah217/KotlinRobotPattern/blob/0f95988fad244f4ad8e54097ac526a12d4587b86/src/test/kotlin/screens/LoginScreen.kt#L7

Please let me know, if you require more info.

**Comment by imurchie** [comment]
Before trying to get that element could you get the source, to see what the espresso framework considers to be there?

**Comment by priyankshah217** [comment]
Okie Let me print source in both instrumentations. Here I wonder so much difference in page sources. 

https://gist.github.com/priyankshah217/2541a87a6400545da7cb97d96ecf97f3#file-espresso_pagesource-xml

https://gist.github.com/priyankshah217/2541a87a6400545da7cb97d96ecf97f3#file-uiautomator2_pagesource-xml

**Comment by mykola-mokhnach** [comment]
> Okie Let me print source in both instrumentations. Here I wonder so much difference in page sources.

This is expected. UiAutomator2 and Espresso use two absolutely different automation approaches.

**Comment by priyankshah217** [comment]
I agree, but that way older way of location strategies won't work.
Anyway, by changing location stragergies, it worked. 
`private val loginConfirmButton = MobileBy.xpath("//com.facebook.react.views.text.ReactTextView[@text='LOG IN']")
`

Closing this issue.

Thanks for your support.
