### ISSUE TITLE
GetOrientation can be null because of no elementId

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-espresso-driver#479]
https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetOrientation.kt#L30
should be getting root view, I assume

---

https://dev.azure.com/kazucocoa/ruby_lib_core_func/_build/results?buildId=1260

**Comment by KazuCocoa** [comment]
am working

**Comment by mykola-mokhnach** [comment]
> should be getting root view, I assume

yeah, look like copypaste issue
