### ISSUE TITLE
unable to get webview context

### ISSUE THREAD

**Issue by tracyzhuyq** [appium/appium-espresso-driver#494]
One question: in order to get webview context, is it necessary to set to true the setWebContentsDebuggingEnabled property on the android.webkit.WebView element, as using UIAutomator2?

Background: The app is a hybrid app and with setWebContentsDebuggingEnabled set to false. The app can be launched, but unable to get webview context using driver.getContextHandlers(). It returns "NATIVE_APP" only although there is webview.

**Comment by KazuCocoa** [comment]
Yes, basically if you want to access to the webview.

Or you can use `mobile:webAtoms` to access to the webview on Espresso. It follows 
 https://developer.android.com/training/testing/espresso/web .
https://github.com/appium/appium/blob/b12c6e22e316db2f0becf8f3754549811a57b0f4/docs/en/commands/mobile-command.md#L141

https://discuss.appium.io also should help for such question
