### ISSUE TITLE
Espresso datamatcher in java

### ISSUE THREAD

**Issue by ganjarpanji** [appium/appium-espresso-driver#500]
I tried to find element with this espresso snippet : 
`onData(hasToString(startsWith("SETTINGS")))`

in appium : 
`driver.findElement(MobileBy.androidDataMatcher("{\"name\": \"hasToString\",\"args\": [\"name\":\"startsWith\", \"args\": \"SETTINGS\"]}"))`

is this a correct way?

**Comment by KazuCocoa** [comment]
Yes, it looks correct.
https://appium.io/docs/en/writing-running-appium/android/espresso-datamatcher-selector/

**Comment by KazuCocoa** [comment]
https://discuss.appium.io is also a good place to ask such question
