### ISSUE TITLE
Unable to local element by resource-id

### ISSUE THREAD

**Issue by hunzai** [appium/appium-espresso-driver#504]
I have following layout for one of Views. I am not able to locate any of these elements with resource-id. But espresso is able to locate `android:id/content` . I know where was a PR with following code

``` 
if (!selector.matches(ID_PATTERN)) {
                    selector = String.format("%s:id/%s", context.getPackageName(), selector);
                    logger.info(String.format("Rewrote Id selector to '%s'", selector));
 }

```  

I am not sure why we are appending package name here ? If I pass `driver.findElement("id", "meta_nav_wrapper_mobile")`  I am not able to locate the element.

I am doing following
- using appium with espresso-driver. 
- I checked out https://github.com/appium/appium-espresso-driver and build locally ` espresso-server`  and used `app-debug-androidTest.apk`

May be I am not using correct strategy ? 
- I am using correct strategy to locate element i.e  `driver.findElement("id", "meta_nav_wrapper_mobile")` ? 
 - see screen shot attached

![image](https://user-images.githubusercontent.com/208305/66829598-fd269900-ef53-11e9-8de0-9e661054338d.png)

-

**Comment by mykola-mokhnach** [comment]
Are you sure you inspect the app with Espresso selected as the backend?

**Comment by hunzai** [comment]
@thanks @mykola-mokhnach I am using now espresso driver in Appium capabilities. The DOM looks different with Espresso driver. Web content is loaded into following 
`<com.reactnativecommunity.webview.RNCWebViewManager index="0" package="com.COMPANY.app.COMPANY" class="com.reactnativecommunity.webview.RNCWebViewManager" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="true" long-clickable="false" password="false" selected="false" visible="true" bounds="[0,297][1080,2028]" viewIndex="37" />`

When I inspect using Appium I can't see  elements /content in side `com.reactnativecommunity.webview.RNCWebViewManager`  so basically the content is rendered.

**Comment by hunzai** [comment]
@mykola-mokhnach any hints how I can get elements ?

**Comment by KazuCocoa** [comment]
What about adding `testID` to the element?
Perhaps, if the element could not find with adding testID, Espresso (Android framework) cannot find it on ReactNative.

**Comment by hunzai** [comment]
There are testIDs for web element but I can't see them when I use espresso as backend and open in appium

**Comment by KazuCocoa** [comment]
oh, okay.
Appium can handle them via [mobile:webAtoms](http://appium.io/docs/en/commands/mobile-command/) if the element can be handled by Espresso's [webatom](https://developer.android.com/training/testing/espresso/web).
(The source command does not include elements which only can access via such webatoms.)

So, potentially, you can try to find elements inside reactnative-webview via the webatom.
