### ISSUE TITLE
[Espresso] [Instrumentation] [STDERR] java.lang.SecurityException: Permission Denial:does not have a signature matching the target

### ISSUE THREAD

**Issue by Vyshakh-01** [appium/appium-espresso-driver#509]
Appium Version:  1.15.1
DEVICE API: 28
MAC O.S: macOS High Sierra 10.13.6

Not able to execute backdoor functionalities since Espresso is asking for the permission, attach logs for the reference.

Any help will be appreciated.
- noSign:true logs
- noSign:false logs

https://gist.github.com/Vyshakh-01/bace19a79d3d9f90513a58c4db3054ec

**Comment by Vyshakh-01** [comment]
@jlipps We tried with your test app {https://github.com/cloudgrey-io/the-app}, but when we tried with our test app we encountered above issue. we would like to know if we have to add any extra permission in our test app.

**Comment by rajdeepv** [comment]
@Vyshakh-01 It has nothing to do with the backdoor. 
This error means the app under test and espresso server are signed with different keys. I recommend removing noSign capability completely and set "forceEspressoRebuild" capability to true

**Comment by Vyshakh-01** [comment]
"forceEspressoRebuild" worked, Thank you
