### ISSUE TITLE
Could not find the build.gradle file under /usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/espresso-server/app

### ISSUE THREAD

**Issue by nathiyatesting** [appium/appium-espresso-driver#513]
I could not find the following file build.gradle under the path '/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/espresso-server/app'. Will it available already or de we need to create id?

Can you please help me in locate the file.

**Comment by imurchie** [comment]
What _is_ in `/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/espresso-server/app`? What version of Appium is this?

**Comment by nathiyatesting** [comment]
@imurchie  Thanks for the immediate reply.Am using the appium 1.15.1 .   Inside the /usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/espresso-server/app folder am having only build folder and inside build folder outputs/apk/debug/app-debug-androidTest.apk

**Comment by KazuCocoa** [comment]
It is expected since Appium only re-packages the app under test with `AndroidManifest-test.xml` and appium sign key. Appium does not gradle build espresso server on user local.

You should get this repository to build your own customised espresso apk for now.
