### ISSUE TITLE
 io.appium.espressoserver.test does not have a signature matching the target com.quvideo.vivamini

### ISSUE THREAD

**Issue by 18757553178** [appium/appium-espresso-driver#529]
Hi, how can I solve this problem？

log：[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.quvideo.vivamini.app.ui.SplashActivity","appPackage":"com.quvideo.vivamini","forceEspressoRebuild":true,"automationName":"Espresso","platformName":"Android","UDID":"R59M600DC6L","deviceName":"Android Emulator"},null,{"firstMatch":[{"UDID":"R59M600DC6L","appium:appActivity":"com.quvideo.vivamini.app.ui.SplashActivity","appium:appPackage":"com.quvideo.vivamini","appium:automationName":"Espresso","appium:deviceName":"Android Emulator","forceEspressoRebuild":true,"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1578300158299 (16:42:38 GMT+0800 (CST))
[BaseDriver] The capabilities ["UDID","forceEspressoRebuild"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.16.0-beta.3 creating new EspressoDriver (v1.19.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "appium:UDID": "R59M600DC6L",
[debug] [BaseDriver]     "appium:forceEspressoRebuild": true,
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:appActivity": "com.quvideo.vivamini.app.ui.SplashActivity",
[debug] [BaseDriver]     "appium:appPackage": "com.quvideo.vivamini",
[debug] [BaseDriver]     "appium:automationName": "Espresso",
[debug] [BaseDriver]     "appium:deviceName": "Android Emulator"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   UDID
[BaseDriver] Session created with session id: f51826de-0c43-4b44-a7e5-d6d4778a7e8b
[Espresso] EspressoDriver version: 1.19.0
[ADB] Using 'adb' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] Connected devices: [{"udid":"R59M600DC6L","state":"device"}]
[AndroidDriver] Using device: R59M600DC6L
[ADB] Using 'adb' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb'
[debug] [ADB] Setting device id to R59M600DC6L
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 28
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 9
[debug] [ADB] Device API level: 28
[Espresso] Relaxing hidden api policy
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings put global hidden_api_policy_p_apps 1'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings put global hidden_api_policy 1'
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L wait-for-device'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.16.2' >= '2.16.2')
[debug] [ADB] There is no need to install/upgrade '/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell pgrep -f io\\.appium\\.settings'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings get global animator_duration_scale'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings get global transition_animation_scale'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings get global window_animation_scale'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus disable'
[debug] [Espresso] Forwarding Espresso Server port 6791 to 8300
[debug] [ADB] Forwarding system: 8300 to device: 6791
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L forward tcp\:8300 tcp\:6791'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [Espresso] No app capability. Assuming it is already on the device
[debug] [ADB] Getting install status for com.quvideo.vivamini
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell dumpsys package com.quvideo.vivamini'
[debug] [ADB] 'com.quvideo.vivamini' is installed
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell am force-stop com.quvideo.vivamini'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell pm clear com.quvideo.vivamini'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.quvideo.vivamini' application (stop and clear)
[debug] [Espresso] 'forceEspressoRebuild' capability is enabled
[debug] [Espresso] Deleting the obsolete Espresso server package '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk'
[Espresso] Building espresso server
[debug] [Espresso] build dir: /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/espresso-server
[debug] [Espresso] Copying espresso server template from (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/espresso-server to /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/espresso-server)
[debug] [Espresso] Beginning build with command './gradlew assembleAndroidTest' in directory '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/espresso-server'
[debug] [Espresso] Output from Gradle will not be logged. To change this, use 'showGradleLog' desired capability
[Espresso] Repackaging espresso server for: 'com.quvideo.vivamini'
[Espresso] Creating new manifest: '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/AndroidManifest.xml'
[debug] [ADB] Found the most recent Android platform: {"platform":"android-29","platformPath":"/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platforms/android-29"}
[ADB] Using 'aapt2' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/aapt2'
[debug] [ADB] Compiling the manifest using '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/aapt2 link -o /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/AndroidManifest.xml.apk --manifest /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/AndroidManifest.xml --rename-manifest-package io.appium.espressoserver.test --rename-instrumentation-target-package com.quvideo.vivamini -I /Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platforms/android-29/android.jar -v'
[debug] [ADB] Compiled the manifest at '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/AndroidManifest.xml.apk'
[debug] [ADB] Inserting manifest '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/AndroidManifest.xml', src: '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/espresso-server/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk', dst: '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk'
[debug] [ADB] Unzipping '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/AndroidManifest.xml.apk' to '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T'
[debug] [ADB] Unzip successful
[ADB] Using 'aapt' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/aapt'
[debug] [ADB] Moving manifest
[debug] [ADB] Manifest insertion into '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' is completed
[Espresso] Repackaged espresso server ready: '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk'
[debug] [ADB] Checking app cert for /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk
[ADB] Using 'apksigner' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner'
[debug] [ADB] Starting '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner' with args '["verify","--print-certs","/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk"]'
[ADB] Got an error during apksigner execution: Command '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner verify --print-certs /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' exited with code 1
[ADB] apksigner stderr: DOES NOT VERIFY
[ADB] ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?
[ADB] 
[debug] [ADB] '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' is not signed with debug cert
[ADB] Using 'zipalign' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/zipalign'
[debug] [ADB] /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' with default cert
[debug] [ADB] Starting '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner' with args '["sign","--key","/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8","--cert","/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem","/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk"]'
[debug] [ADB] Uninstalling io.appium.espressoserver.test
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is installed
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell am force-stop io.appium.espressoserver.test'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L uninstall io.appium.espressoserver.test'
[debug] [ADB] 'adb uninstall io.appium.espressoserver.test' command output: Success
[ADB] io.appium.espressoserver.test was successfully uninstalled
[Espresso] Uninstalled the obsolete Espresso server package from the device under test
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is not installed
[debug] [ADB] App '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' is not installed
[Espresso] Installing Espresso Test Server apk from the target device (path: '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk')
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[debug] [ADB] The count of applications in the cache: 10
[ADB] Caching the application at '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' to '/data/local/tmp/appium_cache/fd3d0b4c1394577009fe6f32cfca1303dd6fc43d.apk'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell mkdir -p /data/local/tmp/appium_cache'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L push /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk /data/local/tmp/appium_cache/fd3d0b4c1394577009fe6f32cfca1303dd6fc43d.apk'
[ADB] The upload of 'io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' (5.04 MB) took 336ms
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell rm -f /data/local/tmp/appium_cache/68efa2107f52c243e173cb47fe2dca7662ae1ebc.apk'
[debug] [ADB] Deleted 1 expired application cache entries
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell pm install /data/local/tmp/appium_cache/fd3d0b4c1394577009fe6f32cfca1303dd6fc43d.apk'
[ADB] The installation of 'io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' took 9807ms
[debug] [ADB] Install command stdout: Success
[Espresso] Installed Espresso Test Server apk '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' (pkg: 'io.appium.espressoserver.test')
[debug] [Espresso] Performing cleanup of automation leftovers
[debug] [Espresso] No obsolete sessions have been detected (Error: socket hang up)
[Espresso] Starting Espresso Server v1.19.0 with cmd: adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","R59M600DC6L","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=13991, uid=13991 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.quvideo.vivamini
[debug] [Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_STATUS: id=ActivityManagerService
[debug] [Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [Espresso] [Instrumentation] [STDERR] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=13991, uid=13991 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.quvideo.vivamini
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.os.Parcel.createException(Parcel.java:1966)
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.os.Parcel.readException(Parcel.java:1934)
[debug] [Espresso] Deleting espresso session
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.os.Parcel.readException(Parcel.java:1884)
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:4356)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.commands.am.Instrument.run(Instrument.java:484)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.commands.am.Am.runInstrument(Am.java:194)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.commands.am.Am.onRun(Am.java:80)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.commands.am.Am.main(Am.java:50)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
[debug] [Espresso] [Instrumentation] [STDERR] Caused by: android.os.RemoteException: Remote stack trace:
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:26918)
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.app.IActivityManager$Stub.onTransact$startInstrumentation$(IActivityManager.java:11163)
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:440)
[debug] [Espresso] [Instrumentation] [STDERR] 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4174)
[debug] [Espresso] [Instrumentation] [STDERR] 	at android.os.Binder.execTransact(Binder.java:739)
[debug] [Espresso] [Instrumentation] [STDERR]
[Espresso] Instrumentation process exited with code 1 from signal null
[Espresso] Instrumentation process died with code 1 and signal null
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell am force-stop com.quvideo.vivamini'
[debug] [Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings delete global hidden_api_policy_p_apps'
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L shell settings delete global hidden_api_policy'
[debug] [ADB] Removing forwarded port socket connection: 8300 
[debug] [ADB] Running '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/platform-tools/adb -P 5037 -s R59M600DC6L forward --remove tcp\:8300'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1578300198307 (16:43:18 GMT+0800 (CST))
[debug] [W3C] Encountered internal error running command: A new session could not be created. Details: java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=13991, uid=13991 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.quvideo.vivamini
[debug] [W3C] 	at android.os.Parcel.createException(Parcel.java:1966)
[debug] [W3C] 	at android.os.Parcel.readException(Parcel.java:1934)
[debug] [W3C] 	at android.os.Parcel.readException(Parcel.java:1884). Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [W3C] Error: java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=13991, uid=13991 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.quvideo.vivamini
[debug] [W3C] 	at android.os.Parcel.createException(Parcel.java:1966)
[debug] [W3C] 	at android.os.Parcel.readException(Parcel.java:1934)
[debug] [W3C] 	at android.os.Parcel.readException(Parcel.java:1884)
[debug] [W3C]     at startDetector (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:227:15)
[debug] [W3C]     at handleOutput (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/subprocess.js:106:32)
[debug] [W3C]     at Socket.proc.stderr.on.chunk (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/subprocess.js:159:48)
[debug] [W3C]     at emitOne (events.js:116:13)
[debug] [W3C]     at Socket.emit (events.js:211:7)
[debug] [W3C]     at addChunk (_stream_readable.js:263:12)
[debug] [W3C]     at readableAddChunk (_stream_readable.js:246:13)
[debug] [W3C]     at Socket.Readable.push (_stream_readable.js:208:10)
[debug] [W3C]     at Pipe.onread (net.js:601:20)
[HTTP] <-- POST /wd/hub/session 500 40012 ms - 1827

**Comment by 18757553178** [comment]
I can start it normally when I use UiAutomator2

**Comment by KazuCocoa** [comment]
What is the app under test's signature?

Espresso server and the app must have the same signature. If yout test app did not have the Appium's signature, how about adding `app` capability to make appium sign with it?

```
[ADB] Using 'apksigner' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner'
[debug] [ADB] Starting '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner' with args '["verify","--print-certs","/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk"]'
[ADB] Got an error during apksigner execution: Command '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/apksigner verify --print-certs /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' exited with code 1
[ADB] apksigner stderr: DOES NOT VERIFY
[ADB] ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?
[ADB]
[debug] [ADB] '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' is not signed with debug cert
[ADB] Using 'zipalign' from '/Users/onepiece/Downloads/toolspath/android/android-sdk-macosx/build-tools/29.0.2/zipalign'
[debug] [ADB] /var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing '/var/folders/yw/2cphjtsn22b_c96vxx20jy000000gn/T/io.appium.espressoserver.test_1.19.0_com.quvideo.vivamini.apk' with default cert
```

https://appium.io/docs/en/drivers/android-espresso/
> you must also include appropriate platformName (=Android), platformVersion, deviceName, and app capabilities, at a minimum.

**Comment by 18757553178** [comment]
I added all the startup capabilities you mentioned, and I added a keystorepath startup capabilities to specify the signature file, or to report this error

**Comment by KazuCocoa** [comment]
Could you share the log with `app` capability as [GITS](https://gist.github.com/new)?

**Comment by sebinjoseph1994** [comment]
@KazuCocoa I'm also facing the same error. I'm trying to access the appium test apk itself and passing the same using app capability. Getting the error 
_[Instrumentation] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=23457, uid=23457 not allowed because package io.appium.espressoserver.test does not have a signature matching the target io.appium.android.apis_

Please find the complete logs here https://gist.github.com/sebinjoseph1994/0628ff1e2ec6b60fe7b1932b58e407be.

**Comment by KazuCocoa** [comment]
Do you have `com.android.settings` binary by yourself?
Espresso framework requires to have the same signature for both the app under test and Appium espresso driver. In most cases, the app under test is your own one.

> Both the server package and the application under test must be signed with the same digital signature. Appium does sign them automatically upon session creation, so this could only be an issue if one wants to test an application, which is already installed on the device (using noReset=true capability).

https://github.com/appium/appium-espresso-driver#requirements

**Comment by sebinjoseph1994** [comment]
@KazuCocoa Thanks for that. The same was getting added from some cache I think. That was the app package I tried before but when later discovered that app needs to be passed and changed that. But the appium server was picking the old one as well. When  I restarted the emulator and appium server, it worked. Thanks for the quick help :)

**Comment by ayush547** [comment]
Hello,
I am facing the same issue, how do I set "io.appium.espressoserver.test" to something else?
Aren't Keystore independent of package name? How can they affect this?
