### ISSUE TITLE
Cannot extract apk info using apkanalyzer. 

### ISSUE THREAD

**Issue by grigoriy2150** [appium/appium-espresso-driver#530]
Appium fails when try to read apk wth apkanalyzer.
`[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Could not find 'apkanalyzer.bat' in ["C:\\Users\\User\\AndroidSDK\\platform-tools\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\emulator\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\tools\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\tools\\bin\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\29.0.2\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\29.0.1\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\29.0.0\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\28.0.3\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\28.0.2\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\28.0.1\\apkanalyzer.bat","C:\\Users\\User\\AndroidSDK\\build-tools\\28.0.0\\apkanalyzer.bat"]. Do you have Android Build Tools installed at 'C:\Users\User\AndroidSDK'?`

Full logs are here:
[full logs](https://github.com/appium/appium-espresso-driver/files/4033953/logs.txt)

In AndroidSDK I have only 'apkanalyzer start up script for UN*X ', but I'm using Windows.

**Comment by KazuCocoa** [comment]
Then, appium uses aapt instead of apkanalyzer as the log `Falling back to aapt.`

**Comment by AvinashVojjala** [comment]
@KazuCocoa 
I am facing the same issue, what is the fix here? I was not sure about it. Thanks.

**Comment by KazuCocoa** [comment]
we expect Android package has `apkanalyzer` or `aapt`. Newer ones should have `apkanalyzer`, but Windows environment did not have it before, probably.

I'm not sure recent ones, but you probably can update your Android environment, ensure `apkanalyzer` or `aapt` exists on your environment and check appium log if the path Appium tries to call correct path to either apkanalyzer or aapt.
