### ISSUE TITLE
autoLaunch: false still starts app

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#531]
I would expect app not to start when `autoLaunch` capability is set to `false`, But, it still launches the app
The app  launch is handled by server-side, but there is no consideration of `autoLaunch` there

**Comment by mykola-mokhnach** [comment]
In Espresso this capability won't work, because we must start the app in order to start the driver and vice versa

**Comment by rajdeepv** [comment]
Technically, yes. However, we can still start just the instrumentation process without starting any activity. starting an activity can be done later by automation code (eg: using deep link)
In my case, there are scenarios when I want to skip app start(first activity start) for profiling app start
If you think it makes sense, I can raise a PR to take `autoLaunch` into account [here](https://github.com/appium/appium-espresso-driver/blob/b182b4d1b24c39950367ea788089fccc024572e8/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt#L39)

**Comment by mykola-mokhnach** [comment]
sure, it worth trying
