### ISSUE TITLE
Disabling animations by default results in unexpected consequence

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#534]
As part of #73 Animations are completely disabled for espresso. This results in some unexpected effects like some images are not loaded (In my case even app logo was missing)
We can still have it disabled by default but there should be an option not to do so. I ran my test by reverting #73 and it worked fine

**Comment by mykola-mokhnach** [comment]
I also like the idea to make the setting configurable

**Comment by mykola-mokhnach** [comment]
and enabled by default

**Comment by rajdeepv** [comment]
I tried with my app keeping animation on, did not face any issues. Maybe there can be other apps with never-ending animations that may not work.

**Comment by KazuCocoa** [comment]
Thanks. It's interesting.

In my memory, a long time ago worked with animation, but espresso started to raise an exception (I forgot which version). But the limitation has been relaxed again.
Ah... or just an error message (not such exception..)

**Comment by rajdeepv** [comment]
@mykola-mokhnach @KazuCocoa I ran the full suite of my app with around 400 tests with animation **ON** and everything looks good
I suggest keeping animation ON by default and utilize(implement) `disableWindowAnimation` capability to disable them if needed

**Comment by nicodn** [comment]
Something else I've noticed that may relate to this is that the animation setting is permanently changed on the test device, it is **not** restored to whatever setting was configured prior to running the tests. I suggest that the driver restore the previous setting after testing is done, perhaps also controlled by a configurable capability.

**Comment by rajdeepv** [comment]
@nicodn There is code that restores it. However, if the test is force killed in the middle, it permanently changes this setting.

**Comment by pr4bh4sh** [comment]
This issue can be closed now.
