### ISSUE TITLE
Appium espresso driver. How to idling resources?

### ISSUE THREAD

**Issue by junaid24** [appium/appium-espresso-driver#545]
Hi. Please explain to me how to use this: https://developer.android.com/training/testing/espresso/idling-resource in Appium Espresso driver.
I appreciate any help, links, code examples for Appium Espresso Driver.
Thank you very much.

**Comment by KazuCocoa** [comment]
Espresso driver does not provide such custom idling resources into appium espresso server.
You should add it properly and build it.
