### ISSUE TITLE
Does it support start instrumentation.startActivitySync(intent, options.toBundle())  ?

### ISSUE THREAD

**Issue by chaooe** [appium/appium-espresso-driver#546]
When i modify the ActivityHelpers.kt. And build it and then replace it on the appium server. It will have below error message.
My device android API is 27. 

`Got an unexpected response with status 500: {"id":"857d4e96-3148-4de9-962f-dd8cb0ba6924","sessionId":null,"value":{"error":"unknown error","message":"java.lang.NoSuchMethodError: No virtual method startActivitySync(Landroid/content/Intent;Landroid/os/Bundle;)Landroid/app/Activity; in class Landroid/app/Instrumentation; or its super classes (declaration of 'android.app.Instrumentation' appears in /system/framework/framework.jar)","stacktrace":"java.lang.NoSuchMethodError: No virtual method startActivitySync(Landroid/content/Intent;Landroid/os/Bundle;)Landroid/app/Activity; in class Landroid/app/Instrumentation; or its super classes (declaration of 'android.app.Instrumentation' appears in /system/framework/framework.jar)\n\tat io.appium.espressoserver.lib.helpers.ActivityHelpers.startActivity(ActivityHelpers.kt:93)\n\tat io.appium.espressoserver.lib.handlers.CreateSession.handleInternal(CreateSession.kt:41)\n\tat io.appium.espressoserver.lib.handlers.CreateSession.handleInternal(CreateSession.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestH...
[W3C] Matched W3C error code 'unknown error' to UnknownError`

**Comment by KazuCocoa** [comment]
https://developer.android.com/reference/android/app/Instrumentation.html#startActivitySync(android.content.Intent,%20android.os.Bundle) requires API level 28. So, your case should not work.

**Comment by chaooe** [comment]
We can use another way to support startActivity which have option
`val options = ActivityOptions.makeBasic()
        options.launchDisplayId = 1
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        context.startActivity(intent, options.toBundle())`
so we can use support it  option.

**Comment by chaooe** [comment]
@KazuCocoa

**Comment by KazuCocoa** [comment]
We're happy to review your PR since you already have an idea :)

**Comment by chaooe** [comment]
@KazuCocoa Please help to review it.https://github.com/appium/appium-espresso-driver/pull/557
As i am a new guy for kotlin and java. i don't know how to write unit test by kt.
