### ISSUE TITLE
Cache Views instead of ViewMatchers

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-espresso-driver#57]
In Espresso, if you try matching a view using a selector that matches multiple views, it will throw an 'AmbiguousViewMatcher' exception.

What we ought to do is catch this exception, and if we encounter it, fallback to the selector that returns a List of elements and then just return the first item on the list.

We could _always_ just get elements in list form and return the first, but I'd be concerned that we'd be missing out on performance benefits.

**Comment by jlipps** [comment]
seems reasonable to me.

**Comment by saikrishna321** [comment]
@dpgraham @mykola-mokhnach  this issue still exists  

https://gist.github.com/saikrishna321/6a80580f132f9eed7505910d72ace825

**Comment by mykola-mokhnach** [comment]
@saikrishna321 Can you please get the full stack trace from adb logcat output?

**Comment by saikrishna321** [comment]
@mykola-mokhnach here you go https://gist.github.com/saikrishna321/aabffac2e7c898f82b54d769bbf4a765

**Comment by mykola-mokhnach** [comment]
It looks like the server source in the module is outdated. @dpgraham Is the server apk built and versioned automatically after a new driver version has been published?

**Comment by dpgraham** [comment]
I didn't do that. It's been a while since I've worked on this.

I guess I need to build the APK before doing a version/publish?

**Comment by mykola-mokhnach** [comment]
I'd rather add auto server building to prepublish tasks, like we did in UIA2. @imurchie can you help with that?

**Comment by dpgraham** [comment]
I'm changing this to instead of caching ViewMatcher we'll cache Views. This is because ViewMatcher goes stale as soon as you use it and thus you can't do more than one operation on a ViewMatcher. It would be simple enough to refactor it to just cache the actual View reference and then if the View doesn't exist anymore, through a `StaleElementException`.
