### ISSUE TITLE
Espresso could not start the server

### ISSUE THREAD

**Issue by vzenzo** [appium/appium-espresso-driver#588]
So I have been trying to switch from UIAutomator2 to Espresso, 
it says "Just change name of automation capability"

I did and it doesn't work, at all...I have moved from maven to gradle, changed automation name, asked developers to implement espresso, and it does not work...no matter what I try I get this message repeated several times:

```
      org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: 'gradlew.bat -PappiumTargetPackage\=my.package.application.com assembleAndroidTest')
Gradle error message:

,
,
,
,
,
,
,
,
,
,
,
,
,
,
Driver info: driver.version: AppiumDriver
remote stacktrace: Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: 'gradlew.bat -PappiumTargetPackage\=my.package.application.com assembleAndroidTest')
Gradle error message:
```

If I change automation name back to UIAutomator2 it works perfectly fine but setting up and trying to start espresso is giving me headaches now

**Comment by mykola-mokhnach** [comment]
- We don't test the driver on Windows. All developers use either Linux or Mac OS. 
- The provided information is not enough to assume anything. The full server log is needed containing the gradle error stack.

**Comment by ctansky** [comment]
I am getting the same error:  remote stacktrace: Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: 'gradlew.bat -PappiumTargetPackage\=my.package.application.com assembleAndroidTest')

[espresso_appium_log.txt](https://github.com/appium/appium-espresso-driver/files/4949688/espresso_appium_log.txt)

My build gradle dependencies in my project

 androidTestImplementation 'androidx.test:rules:1.1.0'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.1.0'

using gradle version distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by mykola-mokhnach** [comment]
@ctansky Consider changing your Java version or Gradle version: https://github.com/exercism/support/issues/73

**Comment by ctansky** [comment]
that worked for me thanks!
