### ISSUE TITLE
[FeatureRequest] add ability for client to get back the output of `adb shell am instrumentation ...`

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#590]
I want to detect if a test has failed due to the app under test crashing (Crashes are usually a critical priority and needs to be highlighted over other failure types). For our Non-Appium instrumentation tests, I check if `adb shell am instrumentation ....` command returns `results=Bundle[{shortMsg=Process crashed.}]` which indicates a crash. I am not able to do the same with Appium because it doesn't return this detail to the client and there is no such contract. It will be really nice to pass this info to client in some way

**Comment by mykola-mokhnach** [comment]
Please try if https://github.com/appium/appium-espresso-driver/pull/591 works for you

**Comment by rajdeepv** [comment]
Yes, #591 is working for me, Thanks a lot for the quick help

**Comment by mykola-mokhnach** [comment]
The change has been published to beta
