### ISSUE TITLE
Driver failed to start

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium-espresso-driver#60]
any idea when it start working with basic functions? thanks!

logs https://gist.github.com/amedvedjev/2ea38a9323485f7d2412ade6bce46902

latest appium server: **v1.6.6-beta.4** with same latest java-client: **5.0.0-BETA9**

**Comment by argeas** [comment]
Having a similar issue. 

android 6.0.1 LG G2
appium: v1.6.6-beta.4
mac osx: sierra 10.12.3
java version "1.8.0_121"

I believe the espresso driver fails to start.. look at logs by the end... 
( in the stack trace the (DeviceCapabilities.java:31) is this line:
driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

https://gist.github.com/argeas/1062fdbb4d64e06186125e2556a3dcd0

**Comment by amedvedjev** [comment]
@jlipps @dpgraham will be really nice start using espresso. the speed is in times faster (tried with Android Studio)

**Comment by argeas** [comment]
@amedvedjev if haven't tried disabling animations from developer options already, you should try it ! it makes things significantly faster when testing.

**Comment by dpgraham** [comment]
@amedvedjev It's on our roadmap. I too would like to get going with Espresso. The speed's faster and also I"m looking at introducing a selector strategy that lets you target elements that are offscreen.

**Comment by dpgraham** [comment]
We're going to get going with development on this soon.
