### ISSUE TITLE
`espressoBuildConfig` should be able to take a JSON object directly, instead of a path to a file

### ISSUE THREAD

**Issue by EdwardDrapkin** [appium/appium-espresso-driver#608]
In some cases (e.g. Saucelabs) it is prohibitively difficult to upload a file to the VM running the Espresso build server, so the Espresso driver cannot read the config that's local to the client.  Allowing us to just attach the build config to the capabilities object would alleviate this problem.

**Comment by mykola-mokhnach** [comment]
The patch has been published in appium@beta

**Comment by EdwardDrapkin** [comment]
Wow, thanks!  That was the fastest open source feature turn around I've ever been a part of :)
