### ISSUE TITLE
feat: EspressoBuildConfig - override hardcoded dependencies to avoid dependencies issues with AUT

### ISSUE THREAD

**Issue by TomBAMU** [appium/appium-espresso-driver#611]
Hi there,

considering that the AUT is not compatible with dependencies of the espresso-server app, it should be possible to override dependencies with the "additionalDependencies". These problems occur since Appium-Version 1.18.x

Observation: During execution the AUT crashes due to an error loading different dependencies. In our case the issue occurs caused by the hard-coded  version of "com.google.android.material:material:1.2.1", which is incompatible with our AUT. There should be a mechanism to manipulate those dependency version. My suggestion would be, a mechanism that overrides existing dependencies in the build-script of the espresso server, if the additionalDependencies contain a matching dependency.

Current behaviour if one dependency is contained in different versions in both sources, build.gradle and espressoBuildConfig, the gradle build fails

Would this be a valid option for the espresso driver team? Any other sugesstions how to challenge this?

**Comment by KazuCocoa** [comment]
The material lib should be in additionalAppDependencies as a configurable deps, I think

**Comment by KazuCocoa** [comment]
Now, the material lib is optional. https://github.com/appium/appium-espresso-driver/pull/616
You can add the dependency as additionalDependencies if needed
