### ISSUE TITLE
Unable to interact in PIP(Picture In Picture) mode

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#671]
I was testing an app that supports PIP mode. After minimizing the app, the mini window is not interactable. page source endpoint raises NoActivityResumedException. The mini window is part of the app's context so I would assume it will be interactable. I also used calabash which is based on instrumentation and it can interact the PIP window due to the way it gets the rootView and the dump.
I tried to find the source of the issue, and to me, it looks like the espresso doesn't support PIP. Still, It will be great to have other experts here asserting my assumption and clarify this.

**Comment by KazuCocoa** [comment]
Not espresso, but what about enabling with/without `enableMultiWindows` in UIA2 driver?
(I haven't dug well when we got https://github.com/appium/appium/issues/15116 )

**Comment by rajdeepv** [comment]
Thanks
