### ISSUE TITLE
Appium desktop v1.21.0 unsable to launch debug app by espresso driver

### ISSUE THREAD

**Issue by TerryCarry** [appium/appium-espresso-driver#681]
Hi masters,
I'm encountering error when trying to use appium desktop for espresso driver, and here is the error code:

[Instrumentation] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=6840, uid=6840 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.xxxxx.xx.debug

and the capabilities:
{
  "automationName": "Espresso",
  "platformName": "Android",
  "deviceName": "qa_1",
  "udid": "emulator-5554",
  "showGradleLog": true,
  "appPackage": "com.xxxxx.xx.debug",
  "noReset": true,
  "forceEspressoRebuild": true,
  "noSign": true
}

I've tried some the solutions here, but still get the same result:
1. Add dependency as https://developer.android.com/training/testing/espresso/setup#groovy mentioned, and re-build the app.
2. Clean all data in app, and re-install app on emulator.
3. Reboot emulator
4. Restart appium desktop
5. Even copy this apk to another machine

The one thing that got me confused is the description in https://github.com/appium/appium-espresso-driver#troubleshooting,
"Espresso requires the debug APK and app-under-test APK (AUT) to have the same signature. It automatically signs the AUT with the io.appium.espressoserver.test signature. This may have problems if you're using an outdated Android SDK tools and/or an outdated Java version."

1. How do I check if these two signature are the same?
2. if they don't, how to i sign them?
3. Is anything i'm missing here?

**Comment by KazuCocoa** [comment]
The espresso driver must have the same signature with `appPackage`.

You can use https://github.com/appium/appium-espresso-driver#app-signing to sign the espresso driver with he same keystore of the app, or you can set `app` capability to sign the app with appium's default keys.

> Both the server package and the application under test must be signed with the same digital signature. Appium does sign them automatically upon session creation, so this could only be an issue if one wants to test an application, which is already installed on the device (using noReset=true capability).

https://github.com/appium/appium-espresso-driver#requirements

https://developer.android.com/studio/command-line/apksigner#usage-verify can check signature.

**Comment by KazuCocoa** [comment]
Asking https://discuss.appium.io/ may also help

**Comment by TerryCarry** [comment]
@KazuCocoa thanks for the feedback, i still got some questions and hopefully you could help me with it.
1. Why does espresso need to do this signature thing while uiautomator don't?
2. About https://github.com/appium/appium-espresso-driver#app-signing, can you be more specific about where i can find key sotre of the app, and what exactly should i do in my capabilities (keystorePassword/keyAlias/keyPassword, these three keys I'm not sure what's the value here...)? 
3. Sorry if i ask stupid questions, I'm really new to this, I think it will be helpful for a new leaner like me who tries to build up espresso with appium.
Thanks.

**Comment by KazuCocoa** [comment]
1. It is by the design of espresso framework https://developer.android.com/training/testing/espresso which is backend of appium-espresso-driver
2. Generally when you build an android app, you/your developer use a keystore. If it was a release built, probably your developer knows its keystore. (General Android thing)
    - If you'd like to test which has the release keystore, you should sign espresso-server by Appium with it. Generally, you should specify `keystorePath`, `keystorePassword` and `useKeystore`. Others depend on your keystore preference. https://developer.android.com/training/articles/keystore for more details
3. Current questions are based on Android Espresso itself (not Appium specific), so I think what we can do as our best effort (by volunteer mainly members) is links to official Espresso stuff so far. Their Android documentation also has been up-to-date. It is very helpful/welcome who can contribute their time to appending/updating our documentation and maintain them...
    - Btw, our root documentation about espresso driver is https://appium.io/docs/en/drivers/android-espresso. Its [minimal requirement](https://appium.io/docs/en/drivers/android-espresso/#usage) expects to use `app`, so I'd recommend you to try with 'app' (like any sample apps etc) first. With more capabilities like keystore requires more additional Android knowledge in general. (Espresso architecture itself requires more Android knowledge than UIA2)

**Comment by TerryCarry** [comment]
@KazuCocoa Thanks again. Now I got another error lol...

Error: 
MJSONWP] Encountered internal error running command: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumZipAlign\=true -PappiumKeystoreFile\=/Users/terry/temp/xxxxx/miscs/release/debug.keystore -PappiumKeystorePassword\=android -PappiumKeyAlias\=androiddebugkey -PappiumKeyPassword\=android -PappiumTargetPackage\=com.xxxxx.debug app\:assembleAndroidTest')
[MJSONWP] Gradle error message:
[MJSONWP] 
[MJSONWP] [STDERR] ,
[MJSONWP] [STDERR] FAILURE: Build failed with an exception.,
[MJSONWP] [STDERR] ,
[MJSONWP] [STDERR] * Where:,
[MJSONWP] [STDERR] Build file '/private/var/folders/fl/1nm21vhs6k14r_s_1r__nsgm0000gn/T/espresso-server-emulator-5554/app/build.gradle.kts' line: 132,
[MJSONWP] [STDERR] ,
[MJSONWP] [STDERR] * What went wrong:,
[MJSONWP] [STDERR] class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap'),
[MJSONWP] [STDERR] ,
[MJSONWP] [STDERR] * Try:,
[MJSONWP] [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[MJSONWP] [STDERR] ,
[MJSONWP] [STDERR] * Get more help at https://help.gradle.org,
[MJSONWP] [STDERR] ,
[MJSONWP] [STDERR] BUILD FAILED in 827ms. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[MJSONWP] Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumZipAlign\=true -PappiumKeystoreFile\=/Users/terry/temp/xxxxx/miscs/release/debug.keystore -PappiumKeystorePassword\=android -PappiumKeyAlias\=androiddebugkey -PappiumKeyPassword\=android -PappiumTargetPackage\=com.xxxxx.debug app\:assembleAndroidTest')

I'm not sure if it's the capbilities i set that was wrong?
{
  "automationName": "Espresso",
  "platformName": "Android",
  "deviceName": "twqa_1",
  "udid": "emulator-5554",
  "showGradleLog": true,
  "appPackage": "com.xxxxx.debug",
  "useKeystore": true,
  "keystorePath": "/Users/terry/temp/xxxxx/miscs/release/debug.keystore",
  "keystorePassword": "android",
  "keyAlias": "androiddebugkey",
  "keyPassword": "android",
  "app": "/Users/terry/temp/xxxxx/app/build/outputs/apk/base.apk",
  "forceEspressoRebuild": true
}

**Comment by mykola-mokhnach** [comment]
@TerryCarry This looks like a bug
Please try if the fix https://github.com/appium/appium-espresso-driver/pull/683 works for you

**Comment by TerryCarry** [comment]
Hi @KazuCocoa master, it seems that you updated the build.gradle.kts, does this change migrated to appium desktop application?

**Comment by TerryCarry** [comment]
if dont, could you let me know how i can replace these two lines into the applicaiton by myself?

**Comment by TerryCarry** [comment]
hi @KazuCocoa @mykola-mokhnach , I passed the signature checking, and stuck at following step:

[Espresso] Performing cleanup of automation leftovers
[Espresso] No obsolete sessions have been detected (socket hang up)
[Espresso] Starting Espresso Server v1.45.2 with cmd: adb shell am instrument -w -e debug false -e disableAnalytics true io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug",false,"-e","disableAnalytics",true,"io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[Espresso] Waiting up to 45000ms for Espresso server to be online
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[Espresso] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Espresso] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[Espresso] Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details

Is this another bug? Or I did something wrong here?

**Comment by KazuCocoa** [comment]
Did you read the logcat as _Check the Appium server log and the logcat output for more details_?

**Comment by TerryCarry** [comment]
Appium Server Log:

[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug",false,"-e","disableAnalytics",true,"io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[Espresso] Waiting up to 45000ms for Espresso server to be online
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[WD Proxy] socket hang up
[Espresso] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Espresso] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[Espresso] Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details
[Espresso] Deleting espresso session
[ADB] Running '/Users/Terry/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[ADB] Running '/Users/Terry/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.shopee.sg.debug'
[Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/Terry/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[ADB] Removing forwarded port socket connection: 8300 
[ADB] Running '/Users/Terry/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8300'
[BaseDriver] Event 'newSessionStarted' logged at 1628650318835 (10:51:58 GMT+0800 (台北標準時間))
[MJSONWP] Encountered internal error running command: A new session could not be created. Details: Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[MJSONWP] Error: Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[MJSONWP]     at Object.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[MJSONWP]     at condFn (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:283:18)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:138:26)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:20)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at spin (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:147:14)
[MJSONWP]     at waitForCondition (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:154:10)
[MJSONWP]     at EspressoRunner.startSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:277:7)
[MJSONWP]     at EspressoDriver.startEspressoSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:318:5)
[MJSONWP]     at EspressoDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:188:7)
[MJSONWP]     at AppiumDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 18677 ms - 346
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found for /wd/hub/session
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 211
[HTTP] 


adb Logcat (Not sure what I'm looking at, attached the file for your reference)
[logcat_espresso.log](https://github.com/appium/appium-espresso-driver/files/6965661/logcat_espresso.log)

**Comment by mykola-mokhnach** [comment]
> 08-11 10:51:53.486  4857  4857 D AndroidRuntime: Shutting down VM
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: FATAL EXCEPTION: main
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: Process: com.xxxxx.sg.debug, PID: 4857
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getTargetState()Landroidx/lifecycle/Lifecycle$State; in class Landroidx/lifecycle/Lifecycle$Event; or its super classes (declaration of 'androidx.lifecycle.Lifecycle$Event' appears in /data/app/io.appium.espressoserver.test-X50X76hkKI2PAcvWZFulsA==/base.apk)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at androidx.lifecycle.ProcessLifecycleOwner.attach(ProcessLifecycleOwner.java:159)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at androidx.lifecycle.ProcessLifecycleOwner.init(ProcessLifecycleOwner.java:105)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at androidx.lifecycle.ProcessLifecycleOwnerInitializer.onCreate(ProcessLifecycleOwnerInitializer.java:38)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 08-11 10:51:53.494  4857  4857 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I would try to include the lifecycle dependency to the list of additional dependencies like it was done in https://github.com/appium/appium-espresso-driver/issues/656

**Comment by TerryCarry** [comment]
sorry master, i'm new to this. where can i find all the version of the dependencies defined in https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/build.gradle.kts?

**Comment by KazuCocoa** [comment]
Yes, the file is default dependencies in this espresso driver.
You can add your own necessary dependencies in Espresso with https://github.com/appium/appium-espresso-driver#espresso-build-config
Espresso strongly depends on the app under test, so you should coordinate necessary dependencies with the configuration.

Probably you should specify `androidx.lifecycle` stuff if your app under test referred to the dependency.

**Comment by TerryCarry** [comment]
@KazuCocoa @mykola-mokhnach masters, finally i successfully launch appium espresso driver... thanks so much for your assisstance.
