### ISSUE TITLE
Not able to perform action on element -matches multiple views

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-espresso-driver#70]
@dpgraham i was trying out espresso and finding the initial element throw error

driver.findElementById("");

https://gist.github.com/saikrishna321/38f995dd593648e3496ecba75992a484#file-gistfile1-txt-L1070

**Comment by mykola-mokhnach** [comment]
Please add the logcat output as well

**Comment by mykola-mokhnach** [comment]
Might be related to https://github.com/appium/appium-espresso-driver/issues/57

**Comment by saikrishna321** [comment]
https://gist.github.com/saikrishna321/e9e7bea13c9c2dc6e96ac69f10bc8b75

**Comment by saikrishna321** [comment]
@mykola-mokhnach would [this](https://github.com/appium/appium-espresso-driver/commit/df5f9c71aa25e2a913561de8f15498698bce87d8) fix this issue

**Comment by mykola-mokhnach** [comment]
most likely. you need to build the server from master and check

**Comment by saikrishna321** [comment]
let me try now

**Comment by saikrishna321** [comment]
@mykola-mokhnach its still the same

**Comment by saikrishna321** [comment]
Closing as its fixed with latest espresso-driver 1.0.0-beta8
