### ISSUE TITLE
Move from jcenter to maven

### ISSUE THREAD

**Issue by kkkorez** [appium/appium-espresso-driver#704]
Is there any plan to remove usages of jcenter() repository from your build scripts and migrate your build to other maven repositories?

**Comment by max-kudlyak** [comment]
Greetings gents! Are there any updates here?

**Comment by KazuCocoa** [comment]
The jcenter is already not in current master https://github.com/appium/appium-espresso-driver/search?q=jcenter by https://github.com/appium/appium-espresso-driver/pull/691
(Forgot closing this issue)
