### ISSUE TITLE
Unable to grant permissions with device popups

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium-espresso-driver#724]
I have detected that each time that the device shows a permissions popup over the app we can't interact with this popup or its elements. I have tried to find the elements by:

- Id or Xpath using "com.android.permissioncontroller:id/permission_message"
- Classname using "android.widget.Button"

And the driver doesn't return any value. In Addition I have tried to get the page source in the moment when the popup is shown and the driver crashes before returning any information.

I already know that the capability "autoGrantPermissions=true" skips this kind of popups, but it should be great to interact with this kind of popups to test also how the app manages the situations when the user blocks the permissions.

I have tried with the current version of appium 1.22 and with EspressoDriver version 1.45.3

**Comment by KazuCocoa** [comment]
Did you tried https://github.com/appium/appium-espresso-driver#mobile-changepermissions out?

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @KazuCocoa , no I haven't. My goal would be to click on the system popups to simulate completely the interaction of the user with the device, I have implemented it with UiAutomator2 but it seems that when any system popup is shown, the communication with the driver is paused until I close that popup.

**Comment by mykola-mokhnach** [comment]
This is the global limitation of the Espresso driver itself. It only works in the application sandbox and since these alerts are shown by the system it does not have any access to them. There is a limited support of UiAutomator in this driver (via `mobile` commands). Otherwise I don't have any other advices.

**Comment by KazuCocoa** [comment]
Yes. As mykola's comment, it is a general limitation of espresso framework by Google. It cannot communicate with elements outside the app. It is not appium specific issue, unfortunately.

Espresso framework recommends using https://developer.android.com/reference/androidx/test/rule/GrantPermissionRule to manage permission. The case is the same as when you grant permission to skip the popup.

**Comment by JuanCarlos-Arceredillo** [comment]
Ok, I understand. Thank you @KazuCocoa and @mykola-mokhnach for the information. I will update my tests to work as you suggested.
