### ISSUE TITLE
ComposeNotIdleException: Idling resource timed out: possibly due to compose being busy.

### ISSUE THREAD

**Issue by bronik** [appium/appium-espresso-driver#725]
Hi there! 
I'm facing an issue while getting back from compose to espresso driver after interacting with compose element. 
Just switching between compose and espresso without interacting with elements going ok
[appium logs](https://gist.github.com/bronik/310f8e84ce7050b4292a2630f304ee12)

**Comment by rajdeepv** [comment]
Looks like your app is not idle after the interaction you are doing. Could you please try this
1. Don't switch to compose
2. Do the interaction manually
3. try interacting using espresso as usual. i.e find element `[HTTP] {"using":"xpath","value":"(//Image[@content-desc=\"Close\"])[last()]"}
`
and check if the same issue happens

**Comment by bronik** [comment]
thanks for your answer!
1. that was weird. no one of composable elements were displayed. checking why..
2. everything is fine
3. NoSuchElementException: Can't locate an element by this strategy: By.chained({By.xpath: (//Image[@content-desc="Close"])[last()]})

**Comment by bronik** [comment]
there are no composable elements on the screen when espresso-server launch the app..  
they became visible after setting compose driver or after some random actions in app

checked with appium desktop 1.22.0 + 1.50.1 espresso driver; appium v1.23.0-beta.0 + espresso driver 1.50.1;

**Comment by KazuCocoa** [comment]
What about the logcat?
I haven't dug logcat in compose apps, but I wondered some information was there.

**Comment by bronik** [comment]
[error filtered logs](https://gist.github.com/bronik/2cb9ad7b8dc0f150b5bf52ecae54aafd)

**Comment by KazuCocoa** [comment]
was the link when you called the XPath?

**Comment by bronik** [comment]
what link are we talking about? I didn't get you(

**Comment by KazuCocoa** [comment]
https://gist.github.com/bronik/2cb9ad7b8dc0f150b5bf52ecae54aafd was.
I wonder it was when _ComposeNotIdleException: Idling resource timed out: possibly due to compose being busy._ occurred by calling the xpath

**Comment by bronik** [comment]
line 360 in adb logs --> finding element by xpath (after switching back to espresso)
if I got you right)

**Comment by rajdeepv** [comment]
The compose views do not load until you switch driver to compose. So maybe try the below steps
1. Switch to compose
2. Do the interaction manually
3. Switch to espresso
4. Try finding any element. If you still get that idling resource timed out, it is something to be investigated in the app

One more thing you can try is with an older version of the espresso driver that did not have compose support (some older version of appium release). when you land on compose screen, do the interactions manually and then continue using the espresso driver and you can rule out the issue caused by the compose driver

**Comment by bronik** [comment]
thanks for your comment!

finding elements after your steps works perfectly, just tested

issue reproduce ONLY if i'm trying to interact with some compose element. 
in other words, if i just switch driver to compose and back to espresso - everything is fine. 
everything is fine even after interacting with 'espresso' elements and switching to compose and back. 
but if i'm trying to tap compose element - i'm getting 500 error code in appium logs with message: 
`"message":"androidx.compose.ui.test.junit4.android.ComposeNotIdleException: Idling resource timed out: possibly due to compose being busy.\nIdlingResourceRegistry has the following idling resources registered:\n- [busy] androidx.compose.ui.test.junit4.android.ComposeIdlingResource@23929cc \nAll registered idling resources: Compose-Espresso link"`

**Comment by bronik** [comment]
also interesting(tested with appium inspector):
1) switch to compose
2) find compose element (success)
3) tap on element (tap is success)
4) do nothing ~10sec
5) getting error ComposeNotIdleException

interesting is that error message contains line:
[WD Proxy] Got response with status 500: {"id":"52e550ae-34e7-47d5-bf9f-5a21ca4e8ed8","sessionId":"**1c18816c-2682-448d-ba68-79f862a23340**" 
but each interaction was with session **532b8534-e672-488a-93ce-b32b4adb439a**

is it fine?

[logs](https://gist.github.com/bronik/4945a31c1ae302574008d8e5aad71a62)

**Comment by KazuCocoa** [comment]
`532b8534-e672-488a-93ce-b32b4adb439a` was between the client and appium. 
`[WD Proxy] Got response with status 500: {"id":"52e550ae-34e7-47d5-bf9f-5a21ca4e8ed8","sessionId":"1c18816c-2682-448d-ba68-79f862a23340"` was between appium and espresso server, so the log seems good.
