### ISSUE TITLE
Communication with system dialogs

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium-espresso-driver#727]
I opened a previous issue asking about how to handle the OS permission dialogs [here](https://github.com/appium/appium-espresso-driver/issues/724) which works perfectly with the capability suggested.

Now, I have found a different block with other Android features, like the photo gallery or the camera. I would like to know if there is any workaround designed to simulate or force interactions like:

- Exit from the camera without taking a photo.
- Make a photo and return it to the app.
- Exit from the gallery.
- Select a photo from the gallery.
- Exit from the sharing dialog.

Thank you so much for your support

**Comment by mykola-mokhnach** [comment]
You could try https://github.com/appium/appium-espresso-driver#mobile-uiautomator

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @mykola-mokhnach,

Perfect, I'll try this solution, we only need to click on a few buttons of the OS dialogs so I guess that this solution definitely will work.
