### ISSUE TITLE
Couldn't close the app

### ISSUE THREAD

**Issue by fjrKurniawan** [appium/appium-espresso-driver#730]
Hi, 
I'm using Appium 1.22.1 and I always get this error while executing `driver.closeApp()`

> [HTTP] --> POST /wd/hub/session/7b5ed66b-245d-47d7-b742-beb12125ad5e/appium/app/close
[HTTP] {}
[W3C (7b5ed66b)] Calling AppiumDriver.closeApp() with args: ["7b5ed66b-245d-47d7-b742-beb12125ad5e"]
[W3C (7b5ed66b)] Encountered internal error running command: UnsupportedOperationError: Please quit the session in order to close the application under test
[W3C (7b5ed66b)]     at EspressoDriver.closeApp (/usr/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/commands/general.js:30:9)
[W3C (7b5ed66b)]     at commandExecutor (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[W3C (7b5ed66b)]     at /usr/lib/node_modules/appium/node_modules/async-lock/lib/index.js:146:12
[W3C (7b5ed66b)]     at AsyncLock._promiseTry (/usr/lib/node_modules/appium/node_modules/async-lock/lib/index.js:280:31)
[W3C (7b5ed66b)]     at exec (/usr/lib/node_modules/appium/node_modules/async-lock/lib/index.js:145:9)
[W3C (7b5ed66b)]     at AsyncLock.acquire (/usr/lib/node_modules/appium/node_modules/async-lock/lib/index.js:162:3)
[W3C (7b5ed66b)]     at EspressoDriver.executeCommand (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[W3C (7b5ed66b)]     at AppiumDriver.executeCommand (/usr/lib/node_modules/appium/lib/appium.js:563:36)
[W3C (7b5ed66b)]     at runMicrotasks (<anonymous>)
[W3C (7b5ed66b)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[W3C (7b5ed66b)]     at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/7b5ed66b-245d-47d7-b742-beb12125ad5e/appium/app/close 500 44 ms - 1300

Please advise, thank you!

**Comment by KazuCocoa** [comment]
As the error message, quite the session is the same thing as closeApp in espresso server.

**Comment by fjrKurniawan** [comment]
Hi Kazu,

Is there any way to only reset the app but not reset the session? I need to clear the app data after the scenario.
