### ISSUE TITLE
Workaround for ECONNREFUSED ::1:8300

### ISSUE THREAD

**Issue by josepmc** [appium/appium-espresso-driver#747]
I am opening this issue for anyone stumbling on the same problem that I did face. As the property I reference is not documented in the driver, this might not be the best / long-term solution.

**Problem**

When starting the tests, one might get the following:

> \[debug\] \[Espresso\] \[Instrumentation\] io.appium.espressoserver.EspressoServerRunnerTest:  
> \[debug\] \[WD Proxy\] Matched '/status' to command name 'getStatus'  
> \[debug\] \[WD Proxy\] Proxying \[GET /status\] to \[GET http://localhost:8300/status\] with no body  
> \[WD Proxy\] connect ECONNREFUSED ::1:8300

Alongside a logcat stating 

> /? W/ActivityManager: Crash of app \<app name> running instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner}

This issue might lead one to think that the app is crashing at the start. However, the true fact is that node can't connect to the server.

**Workaround**

Following the explanation from [this link](https://developpaper.com/connect-econnreused-127-0-0-180-exception-resolution/), set the following _undocumented_ property on your capabilities: `'appium:host': '0.0.0.0'`, note that `'appium:remoteAdbHost': '0.0.0.0'` also helps but does set `adb -H 0.0.0.0` which might not be what you desire.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-espresso-driver/pull/748 should do the trick even without setting additional capabilities
