### ISSUE TITLE
Espresso Driver -Find element command got struck if there is no element with Xpath selector

### ISSUE THREAD

**Issue by rockstarrocks2020** [appium/appium-espresso-driver#770]
Facing issue while using find element
Using Appium Java Client 7.6.0
Driver launched as Espresso driver  and did not switch to compose view.
**Issue**
After not finding the element the exception is not thrown and the session got struck in between and after so much of time failing with below error :
[Logcat] Logcat terminated with code 1, signal null
[EspressoDriver@ea6d (245c801a)] Instrumentation process exited with code 0 from signal null

**stack trace**
[HTTP] --> POST /session/0a4ddb1b-69c6-4f77-afb8-da3e58bffc3c/element
[HTTP] {"using":"xpath","value":"//*[contains(@text,'Welcome')]"}
[EspressoDriver@1577 (0a4ddb1b)] Driver proxy active, passing request on via HTTP proxy
[debug] [EspressoDriver@1577 (0a4ddb1b)] Matched '/session/0a4ddb1b-69c6-4f77-afb8-da3e58bffc3c/element' to command name 'findElement'
[debug] [EspressoDriver@1577 (0a4ddb1b)] Proxying [POST /session/0a4ddb1b-69c6-4f77-afb8-da3e58bffc3c/element] to [POST http://127.0.0.1:8300/session/2cbbaaf7-4a49-46f8-9f28-01601620051c/element] with body: {"using":"xpath","value":"//*[contains(@text,'Welcome')]"}
[EspressoDriver@1577 (0a4ddb1b)] Got response with status 404: {"id":"1cf37742-fb12-4d6e-8d86-a1dac1918401","sessionId":"2cbbaaf7-4a49-46f8-9f28-01601620051c","value":{"error":"no such element","message":"Could not find espresso element with strategy XPATH and selector //*[contains(@text,'Welcome')]","stacktrace":"io.appium.espressoserver.lib.handlers.exceptions.NoSuchElementException: Could not find espresso element with strategy XPATH and selector //*[contains(@text,'Welcome')]\n\tat io.appium.espressoserver.lib.handlers.FindElement.handleEspresso(FindElement.kt:39)\n\tat io.appium.espressoserver.lib.handlers.FindElement.handleEspresso(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.invokeStrategy(RequestHandler.kt:35)\n\tat io.appium.espressoserver.lib.handlers.FindElement.invokeStrategy(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.FindElement.invokeStrategy(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handleInternal(RequestHandler.kt:29)\n\tat io.appium.espre...
[Logcat] Logcat terminated with code 1, signal null
[EspressoDriver@ea6d (245c801a)] Instrumentation process exited with code 0 from signal null

**Comment by rajdeepv** [comment]
@rockstarrocks2020 
1. Can you please format the message
2. What version of Appium are you using? If it is 2.0, then please refer to https://github.com/appium/appium-espresso-driver/issues/756#issuecomment-1099265727 
3. If you still face the issue, please attach complete Appium logs and ADB logs from the device

**Comment by rockstarrocks2020** [comment]
@rajdeepv yes I am using 2.0.0-beta.33.

but as mentioned in https://github.com/appium/appium-espresso-driver/issues/756#issuecomment-1099265727 this issue. I don't have option to install base driver, as it is not listed in "appium driver list". and also I have installed two drivers only -- uiautomator2@2.1.0 [installed (NPM)]
- espresso@2.2.1 [installed (NPM)]

could you please let me know  how to achieve this step  in the issue you have mentioned above "Yes, although you have to make sure the particular driver depends on @appium/base-driver@8.4.2+. Perhaps, it would be necessary to reinstall it for this or to wait until https://github.com/appium/appium/issues/16747 is resolved"?

**Comment by KazuCocoa** [comment]
Usually re-install `appium@next` and uia2 driver get the latest ones.
Perhaps the version has the base driver issue version like https://github.com/appium/appium/issues/16850. Then, update the appium beta to latest one will resolve it

**Comment by rockstarrocks2020** [comment]
Seems 2.0.0-beta.33 is the latest and I can see the same version when I install with appium@next.
Appium java client is 7.6.0
UIA2 is uptodate below is the stacktrace after launching the app.could you guys please suggest on this.

[debug] [ADB] Found package: 'in.company' and fully qualified activity name : 'in.SplashActivity'
[debug] [EspressoDriver@b2c1 (3abde286)] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8300/session/6f6dfb2b-d989-4f7e-995a-4a5f859d59d8/appium/device/info] with no body
[debug] [EspressoDriver@b2c1 (3abde286)] Got response with status 200: {"id":"e13741a8-fdea-4bef-8412-2d69c5137598","sessionId":"6f6dfb2b-d989-4f7e-995a-4a5f859d59d8","value":{"realDisplaySize":"1080x2340","apiVersion":"30","carrierName":"IND airtel","platformVersion":"11","timeZone":"Asia/Kolkata","model":"M2004J19C","locale":"en","brand":"Redmi","androidId":"242ad368615895c8","manufacturer":"Xiaomi","displayDensity":440}}
[AppiumDriver@6660] New EspressoDriver session created successfully, session 3abde286-9474-4225-b390-7d5f712df0e8 added to master session list
[debug] [AppiumDriver@6660] Event 'newSessionStarted' logged
   at 1651109404540 (07:00:04 GMT+0530 (India Standard Time).1651109404540 (07:00:04 GMT+0530 (India Standard Time))
[debug] [EspressoDriver@b2c1 (3abde286)] Cached the protocol value 'W3C' for the new session 3abde286-9474-4225-b390-7d5f712df0e8
[debug] [EspressoDriver@b2c1 (3abde286)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"android","app":"/Users/user/Downloads/test.apk","appActivity":"in.Activity","appPackage":"in.company","appWaitActivity":"in.Splash","appWaitDuration":10000000000000,"automationName":"Espresso","espressoBuildConfig":"{\"toolsVersions\": {\"composeVersion\": \"1.1.0-alpha04\", \"compileSdk\":\"31\", \"kotlin\":\"1.5.30\"}}","espressoServerLaunchTimeout":1000000000,"forceEspressoRebuild":true,"noSign":true,"showGradleLog":true,"systemPort":8300,"autoGrantPermissions":true}}
[HTTP] <-- POST /session 200 65577 ms - 663
[HTTP] 
[HTTP] --> POST /session/3abde286-9474-4225-b390-7d5f712df0e8/timeouts
[HTTP] {"implicit":5000}
[debug] [EspressoDriver@b2c1 (3abde286)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,5000,"3abde286-9474-4225-b390-7d5f712df0e8"]
[debug] [EspressoDriver@b2c1 (3abde286)] W3C timeout argument: {"implicit":5000}}
[debug] [EspressoDriver@b2c1 (3abde286)] Set implicit wait to 5000ms
[debug] [EspressoDriver@b2c1 (3abde286)] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /session/3abde286-9474-4225-b390-7d5f712df0e8/timeouts 200 6 ms - 14
[HTTP] 
[HTTP] --> GET /session/3abde286-9474-4225-b390-7d5f712df0e8/source
[HTTP] {}
[EspressoDriver@b2c1 (3abde286)] Driver proxy active, passing request on via HTTP proxy
[debug] [EspressoDriver@b2c1 (3abde286)] Matched '/session/3abde286-9474-4225-b390-7d5f712df0e8/source' to command name 'getPageSource'
[debug] [EspressoDriver@b2c1 (3abde286)] Proxying [GET /session/3abde286-9474-4225-b390-7d5f712df0e8/source] to [GET http://127.0.0.1:8300/session/6f6dfb2b-d989-4f7e-995a-4a5f859d59d8/source] with no body
[debug] [EspressoDriver@b2c1 (3abde286)] Got response with status 200: {"id":"3629db14-6a9d-4a6c-8f68-75562d1fb64a","sessionId":"6f6dfb2b-d989-4f7e-995a-4a5f859d59d8","value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><com.android.internal.policy.DecorView index=\"0\" package=\"in.company\" class=\"com.android.internal.policy.DecorView\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" visible=\"true\" bounds=\"[0,0][1080,2340]\" viewIndex=\"0\">  <android.widget.LinearLayout index=\"0\" package=\"in.company\" class=\"android.widget.LinearLayout\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" visible=\"true\" bounds=\"[0,0][1080,2340]\" viewIndex=\"1\">    <android.view.ViewStub index=\"0\" package=\"in.company\" class=\"android.view.ViewS...
[EspressoDriver@b2c1 (3abde286)] Replacing sessionId 6f6dfb2b-d989-4f7e-995a-4a5f859d59d8 with 3abde286-9474-4225-b390-7d5f712df0e8
[HTTP] <-- GET /session/3abde286-9474-4225-b390-7d5f712df0e8/source 200 1242 ms - 5931
[HTTP] 
[HTTP] --> GET /session/3abde286-9474-4225-b390-7d5f712df0e8/source
[HTTP] {}
[EspressoDriver@b2c1 (3abde286)] Driver proxy active, passing request on via HTTP proxy
[debug] [EspressoDriver@b2c1 (3abde286)] Matched '/session/3abde286-9474-4225-b390-7d5f712df0e8/source' to command name 'getPageSource'
[debug] [EspressoDriver@b2c1 (3abde286)] Proxying [GET /session/3abde286-9474-4225-b390-7d5f712df0e8/source] to [GET http://127.0.0.1:8300/session/6f6dfb2b-d989-4f7e-995a-4a5f859d59d8/source] with no body
[debug] [EspressoDriver@b2c1 (3abde286)] Got response with status 200: {"id":"c3ed33f2-edcf-4ede-9858-a1b99be14556","sessionId":"6f6dfb2b-d989-4f7e-995a-4a5f859d59d8","value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><com.android.internal.policy.DecorView index=\"0\" package=\"in.company\" class=\"com.android.internal.policy.DecorView\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" visible=\"true\" bounds=\"[0,0][1080,2340]\" viewIndex=\"0\">  <android.widget.LinearLayout index=\"0\" package=\"in.company\" class=\"android.widget.LinearLayout\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" visible=\"true\" bounds=\"[0,0][1080,2340]\" viewIndex=\"1\">    <android.view.ViewStub index=\"0\" package=\"in.company\" class=\"android.view.ViewS...
[EspressoDriver@b2c1 (3abde286)] Replacing sessionId 6f6dfb2b-d989-4f7e-995a-4a5f859d59d8 with 3abde286-9474-4225-b390-7d5f712df0e8
[HTTP] <-- GET /session/3abde286-9474-4225-b390-7d5f712df0e8/source 200 101 ms - 5931
[HTTP] 
[HTTP] --> POST /session/3abde286-9474-4225-b390-7d5f712df0e8/element
[HTTP] {"using":"xpath","value":"//*[contains(@text,'Welcome')]"}
[EspressoDriver@b2c1 (3abde286)] Driver proxy active, passing request on via HTTP proxy
[debug] [EspressoDriver@b2c1 (3abde286)] Matched '/session/3abde286-9474-4225-b390-7d5f712df0e8/element' to command name 'findElement'
[debug] [EspressoDriver@b2c1 (3abde286)] Proxying [POST /session/3abde286-9474-4225-b390-7d5f712df0e8/element] to [POST http://127.0.0.1:8300/session/6f6dfb2b-d989-4f7e-995a-4a5f859d59d8/element] with body: {"using":"xpath","value":"//*[contains(@text,'Welcome')]"}
[EspressoDriver@b2c1 (3abde286)] Got response with status 404: {"id":"d7e83f8a-d2cf-416f-9e94-591eec5edff2","sessionId":"6f6dfb2b-d989-4f7e-995a-4a5f859d59d8","value":{"error":"no such element","message":"Could not find espresso element with strategy XPATH and selector //*[contains(@text,'Welcome')]","stacktrace":"io.appium.espressoserver.lib.handlers.exceptions.NoSuchElementException: Could not find espresso element with strategy XPATH and selector //*[contains(@text,'Welcome')]\n\tat io.appium.espressoserver.lib.handlers.FindElement.handleEspresso(FindElement.kt:39)\n\tat io.appium.espressoserver.lib.handlers.FindElement.handleEspresso(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.invokeStrategy(RequestHandler.kt:35)\n\tat io.appium.espressoserver.lib.handlers.FindElement.invokeStrategy(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.FindElement.invokeStrategy(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handleInternal(RequestHandler.kt:29)\n\tat io.appium.espre...

**Comment by KazuCocoa** [comment]
i see. Maybe the espresso driver's base driver is old.
(https://github.com/appium/appium/issues/16747 is working issue to improve this dependency)

let me kick a release to update the base driver in this package.

**Comment by KazuCocoa** [comment]
could you try out espresso driver 2.2.2?

**Comment by rockstarrocks2020** [comment]
@KazuCocoa thanks the session has come out of find element. the issue is fixed thanks
