### ISSUE TITLE
Manifest merging exception with espresso 2.2.2

### ISSUE THREAD

**Issue by rockstarrocks2020** [appium/appium-espresso-driver#772]
Getting Manifest merging exception while trying to install new build of espresso.

Below is the stack-trace:

[debug] [ADB] 'in.company' is not installed
[debug] [ADB] App '/Users/user/Downloads/test.apk' is not installed
[debug] [ADB] Installing '/Users/user/Downloads/test.apk'
[ADB] The application at '/Users/user/Downloads/test.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /Users/user/Downloads/test.apk'
[ADB] The installation of 'test.apk' took 999ms
[debug] [ADB] Install command stdout: Performing Streamed Install
[debug] [ADB] Success
[debug] [EspressoDriver@a865 (d55d314d)] 'forceEspressoRebuild' capability is enabled
[debug] [EspressoDriver@a865 (d55d314d)] Deleting the obsolete Espresso server package '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_2.2.2_in.company_emulator-5554.apk'
[EspressoDriver@a865 (d55d314d)] Loading the build configuration from 'espressoBuildConfig' capability
[EspressoDriver@a865 (d55d314d)] Building espresso server in '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554'
[debug] [EspressoDriver@a865 (d55d314d)] The build folder root could be customized by changing the 'tmpDir' capability
[debug] [EspressoDriver@a865 (d55d314d)] Copying espresso server template from ('/Users/user/.appium/node_modules/appium-espresso-driver/espresso-server' to '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554')
[debug] [Support] Traversed 52 directories and 281 files in 167ms
[debug] [EspressoDriver@a865 (d55d314d)] Bulding espresso server
[debug] [EspressoDriver@a865 (d55d314d)] Beginning build with command '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554/gradlew -PappiumCompileSdk=31 -PappiumKotlin=1.5.30 -PappiumComposeVersion=1.1.0-alpha04 -PappiumTargetPackage=in.comnpany app:assembleAndroidTest' in directory '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554'
[debug] [EspressoDriver@a865 (d55d314d)] Output from Gradle will be logged. To change this, use 'showGradleLog' desired capability
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:preBuild UP-TO-DATE
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:preDebugBuild UP-TO-DATE
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:compileDebugAidl NO-SOURCE
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:compileDebugRenderscript NO-SOURCE
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:generateDebugBuildConfig
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:generateDebugResValues
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:generateDebugResources
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:checkDebugAarMetadata
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:mergeDebugResources
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:createDebugCompatibleScreenManifests
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:extractDeepLinksDebug
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:processDebugMainManifest
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:processDebugManifest
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:preDebugAndroidTestBuild SKIPPED
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:compileDebugAndroidTestAidl NO-SOURCE
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:javaPreCompileDebug
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:processDebugAndroidTestManifest FAILED
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] > Task :app:processDebugManifestForPackage
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] 
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] FAILURE: Build failed with an exception.
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] 
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] * What went wrong:
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] Execution failed for task ':app:processDebugAndroidTestManifest'.
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] > Manifest merging exception
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] 
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] * Try:
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] 
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] * Get more help at https://help.gradle.org
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] 
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDERR] BUILD FAILED in 2m 11s
[EspressoDriver@a865 (d55d314d)] [Gradle] [STDOUT] 11 actionable tasks: 11 executed
[EspressoDriver@a865 (d55d314d)] Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554/gradlew -PappiumCompileSdk\=31 -PappiumKotlin\=1.5.30 -PappiumComposeVersion\=1.1.0-alpha04 -PappiumTargetPackage\=in.company app\:assembleAndroidTest')
[EspressoDriver@a865 (d55d314d)] Gradle error message:
[EspressoDriver@a865 (d55d314d)] 
[EspressoDriver@a865 (d55d314d)] [STDOUT] > Task :app:processDebugManifestForPackage,
[EspressoDriver@a865 (d55d314d)] [STDERR] ,
[EspressoDriver@a865 (d55d314d)] [STDERR] FAILURE: Build failed with an exception.,
[EspressoDriver@a865 (d55d314d)] [STDERR] ,
[EspressoDriver@a865 (d55d314d)] [STDERR] * What went wrong:,
[EspressoDriver@a865 (d55d314d)] [STDERR] Execution failed for task ':app:processDebugAndroidTestManifest'.,
[EspressoDriver@a865 (d55d314d)] [STDERR] > Manifest merging exception,
[EspressoDriver@a865 (d55d314d)] [STDERR] ,
[EspressoDriver@a865 (d55d314d)] [STDERR] * Try:,
[EspressoDriver@a865 (d55d314d)] [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[EspressoDriver@a865 (d55d314d)] [STDERR] ,
[EspressoDriver@a865 (d55d314d)] [STDERR] * Get more help at https://help.gradle.org,
[EspressoDriver@a865 (d55d314d)] [STDERR] ,
[EspressoDriver@a865 (d55d314d)] [STDERR] BUILD FAILED in 2m 11s,
[EspressoDriver@a865 (d55d314d)] [STDOUT] 11 actionable tasks: 11 executed
[debug] [EspressoDriver@a865 (d55d314d)] Deleting espresso session
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop in.company'
[debug] [Logcat] Stopping logcat capture
[EspressoDriver@a865 (d55d314d)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [ADB] Removing forwarded port socket connection: 8300 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8300'
[debug] [AppiumDriver@d128] Event 'newSessionStarted' logged
   at 1651459568194 (08:16:08 GMT+0530 (India Standard Time).1651459568194 (08:16:08 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@d128] Encountered internal error running command: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554/gradlew -PappiumCompileSdk\=31 -PappiumKotlin\=1.5.30 -PappiumComposeVersion\=1.1.0-alpha04 -PappiumTargetPackage\=in.company app\:assembleAndroidTest')
[debug] [AppiumDriver@d128] Gradle error message:
[debug] [AppiumDriver@d128] 
[debug] [AppiumDriver@d128] [STDOUT] > Task :app:processDebugManifestForPackage,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] FAILURE: Build failed with an exception.,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] * What went wrong:,
[debug] [AppiumDriver@d128] [STDERR] Execution failed for task ':app:processDebugAndroidTestManifest'.,
[debug] [AppiumDriver@d128] [STDERR] > Manifest merging exception,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] * Try:,
[debug] [AppiumDriver@d128] [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] * Get more help at https://help.gradle.org,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] BUILD FAILED in 2m 11s,
[debug] [AppiumDriver@d128] [STDOUT] 11 actionable tasks: 11 executed. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [AppiumDriver@d128] Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554/gradlew -PappiumCompileSdk\=31 -PappiumKotlin\=1.5.30 -PappiumComposeVersion\=1.1.0-alpha04 -PappiumTargetPackage\=in.company app\:assembleAndroidTest')
[debug] [AppiumDriver@d128] Gradle error message:
[debug] [AppiumDriver@d128] 
[debug] [AppiumDriver@d128] [STDOUT] > Task :app:processDebugManifestForPackage,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] FAILURE: Build failed with an exception.,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] * What went wrong:,
[debug] [AppiumDriver@d128] [STDERR] Execution failed for task ':app:processDebugAndroidTestManifest'.,
[debug] [AppiumDriver@d128] [STDERR] > Manifest merging exception,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] * Try:,
[debug] [AppiumDriver@d128] [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] * Get more help at https://help.gradle.org,
[debug] [AppiumDriver@d128] [STDERR] ,
[debug] [AppiumDriver@d128] [STDERR] BUILD FAILED in 2m 11s,
[debug] [AppiumDriver@d128] [STDOUT] 11 actionable tasks: 11 executed. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [AppiumDriver@d128]    
   at Object.errorAndThrow (/Users/user/.appium/node_modules/appium-espresso-driver/node_modules/@appium/support/lib/logging.js:111:35 undefined)
[debug] [AppiumDriver@d128]    
   at ServerBuilder.runBuildProcess (/Users/user/.appium/node_modules/appium-espresso-driver/lib/server-builder.js:191:16 undefined)
[debug] [AppiumDriver@d128]    
   at ServerBuilder.build (/Users/user/.appium/node_modules/appium-espresso-driver/lib/server-builder.js:71:5 undefined)
[debug] [AppiumDriver@d128]    
   at EspressoRunner.buildNewModServer (/Users/user/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:189:5 undefined)
[debug] [AppiumDriver@d128]    
   at EspressoRunner.installTestApk (/Users/user/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:147:7 undefined)
[debug] [AppiumDriver@d128]    
   at EspressoDriver.initAUT (/Users/user/.appium/node_modules/appium-espresso-driver/lib/driver.js:551:7 undefined)
[debug] [AppiumDriver@d128]    
   at EspressoDriver.startEspressoSession (/Users/user/.appium/node_modules/appium-espresso-driver/lib/driver.js:421:5 undefined)
[debug] [AppiumDriver@d128]    
   at EspressoDriver.createSession (/Users/user/.appium/node_modules/appium-espresso-driver/lib/driver.js:224:7 undefined)
[debug] [AppiumDriver@d128]    
   at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:298:35 undefined)
[HTTP] <-- POST /session 500 134480 ms - 3486
[HTTP]

**Comment by KazuCocoa** [comment]
> [debug] [AppiumDriver@d128] [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,

What the result of debug logs with `--stacktrace`? the espresso build was the below.
You could build the package with the same command (please modify the path to greadlew)

> /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554/gradlew -PappiumCompileSdk=31 -PappiumKotlin=1.5.30 -PappiumComposeVersion=1.1.0-alpha04 -PappiumTargetPackage=in.comnpany app:assembleAndroidTest' in directory '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/espresso-server-emulator-5554
