### ISSUE TITLE
Unable to build Espresso server due to dependencies

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium-espresso-driver#781]
## The problem

I'm working with espresso from appium desktop, and I want to migrate my tests to appium2 in order to support jetpack compose. After updating appium and espresso driver to the latest version (2.2.6), I have tried to run some tests, but I can't start them because of Gradle errors. I'm not sure if the errors depend on the espressoBuildConfig or not. Please, check the attached log file.

## Environment

* Appium version that exhibits the issue: Appium v2.0.0-beta
* Driver version that exhibits the issue: 2.2.6
* Real device or emulator/simulator: real device

## Details

I have used this espressoBuildConfig settings, that worked with the latest version of Appium Desktop (1.22.3, with espresso 1.45.3 ). The same settings don't work with espresso 2.2.6.
`{
  "toolsVersions": {
    "gradle" : "6.7.1",
    "androidGradlePlugin" : "4.2.0",
    "compileSdk" : 30,
    "minSdk" : 21,
    "targetSdk" : 30,
    "kotlin" : "1.5.31",
    "composeVersion": "1.0.4"
  },
  "additionalAppDependencies": ["com.google.android.material:material:1.4.0", "androidx.lifecycle:lifecycle-extensions:2.1.0"]
}
`
## Link to Appium logs

[error.log](https://github.com/appium/appium-espresso-driver/files/8661260/error.log)

**Comment by KazuCocoa** [comment]
Then, did the compose dependency break the androidx.annotation:annotation versioning...?

```
[debug] [AppiumDriver@4533] Gradle error message:
[debug] [AppiumDriver@4533]
[debug] [AppiumDriver@4533] [STDERR]            Dependency path 'espresso-server-2fa9a321:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.collection:collection:1.1.0' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@4533] [STDERR]            Dependency path 'espresso-server-2fa9a321:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.core:core:1.5.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.2.0',
[debug] [AppiumDriver@4533] [STDERR]            Dependency path 'espresso-server-2fa9a321:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.profileinstaller:profileinstaller:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.startup:startup-runtime:1.0.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@4533] [STDERR]            Dependency path 'espresso-server-2fa9a321:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.savedstate:savedstate:1.0.0' (runtime) --> 'androidx.arch.core:core-common:2.1.0' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@4533] [STDERR]            Dependency path 'espresso-server-2fa9a321:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.core:core:1.5.0' (releaseRuntimePublication) --> 'androidx.versionedparcelable:versionedparcelable:1.1.1' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@4533] [STDERR]            Dependency path 'espresso-server-2fa9a321:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.profileinstaller:profileinstaller:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.startup:startup-runtime:1.0.0' (releaseRuntimePublication) --> 'androidx.tracing:tracing:1.0.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@4533] [STDERR] ,
```

What about adding `androidx.annotation:annotation` versioning dependency explicitly in the espressoBuildConfig?

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @KazuCocoa 

Thanks for the suggestion.

I've tried setting manually as an additional dependency `androidx.annotation:annotation:1.1.0` and `androidx.annotation:annotation:1.2.0`, but the  error log is the same. 

Is there a minimum version of any of the other fields inside the espressoBuildConfig that could affect to this process ?
I'm not sure, maybe I need to use a higher version of gradle or kotlin...

Thanks for your support

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/build.gradle.kts#L90-L138 is all dependencies espresso server has. The `espressoBuildConfig` appends dependencies in placeholders in the file.

mm, potentially https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/build.gradle.kts#L151 affects...? but the version was not in your original log.

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @KazuCocoa ,

When I saw this situation I tried several combinations adding dependencies to the `additionalAppDependencies `, but after checking that none of them worked, I remove them because they aren't necessary using the appium desktop app.

I've updated the json info with these fields:

`{
  "toolsVersions": {

    "gradle" : "7.2",
    "androidGradlePlugin" : "7.0.2",
    "compileSdk" : 30,
    "minSdk" : 21,
    "targetSdk" : 30,
    "kotlin" : "1.5.31",
    "annotation": "1.2.0",
    "composeVersion": "1.0.3" 
    }
    "additionalAppDependencies": ["com.google.android.material:material:1.4.0", "androidx.lifecycle:lifecycle-extensions:2.1.0"]
}`

I've tried different combinations of `composeVersion` with 1.0.3, 1.0.4 and 1.0.5 and different `annotation` versions like 1.1.0 and 1.2.0 but the error that I receive is always the same.




`[debug] [AppiumDriver@7142] [STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.collection:collection:1.1.0' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@7142] [STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.core:core:1.5.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.2.0',
[debug] [AppiumDriver@7142] [STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.profileinstaller:profileinstaller:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.startup:startup-runtime:1.0.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@7142] [STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.savedstate:savedstate:1.0.0' (runtime) --> 'androidx.arch.core:core-common:2.1.0' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@7142] [STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.core:core:1.5.0' (releaseRuntimePublication) --> 'androidx.versionedparcelable:versionedparcelable:1.1.1' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[debug] [AppiumDriver@7142] [STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.profileinstaller:profileinstaller:1.0.3' (releaseVariantReleaseRuntimePublication) --> 'androidx.startup:startup-runtime:1.0.0' (releaseRuntimePublication) --> 'androidx.tracing:tracing:1.0.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.1.0',
`

I'm not sure if I'm missing an important field in the json file or if there is an issue with the versions that I've set that aren't compatible.

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @KazuCocoa 

After several tries we have seen that the issue is related to the incompatibility between the dependencies of our app that uses annotation 1.2.0, and the need of the compose and espresso libraries that need annotation 1.1.0. The only way that we have seen to fix this situation is to mark directly in the gradle file that annotation should be forced with the version that we have set in the JSON file. 

Could you confirm us that this way could be valid ?

Additionally, after build espresso with this change... we have seen that after more than a hundred requests from the code to espresso-driver... each request become slower, until espresso doesn't answer to the requests. I'm not sure if it's a different issue or if it depends on the annotation dependency, because it the first time that we have tested this version of the driver.

We use to work with he latest version espresso that comes with Appium Server GUI that is older than this one.

Thank you for your support

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @KazuCocoa. 

Kindly Reminder :)

Could you help us with this ?

Thank you

**Comment by KazuCocoa** [comment]
What about https://github.com/appium/appium-espresso-driver/pull/787 for the annotation?
You could specify the annotation version as:

```
{
"toolsVersions": {
...
"annotation": "1.2.0"
}
}`
```

For the slowness.
I have no idea about that.
Something logs with timestamp info will help. (Then, please create another issue)

**Comment by activesince93** [comment]
Hi @KazuCocoa, I tried using the `additionalAppDependencies` you suggested. I am still getting the following error. 
```
Driver info: driver.version: AndroidDriver
remote stacktrace: Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/9d/x2zw4vm16s7946lnk6y2f8180000gn/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage\=me.app.code.debug app\:assembleAndroidTest')
Gradle error message:

[STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.core:core:1.5.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.2.0',
[STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.savedstate:savedstate:1.1.0' (releaseRuntimePublication) --> 'androidx.arch.core:core-common:2.1.0' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.lifecycle:lifecycle-runtime:2.3.0' (releaseRuntimePublication) --> 'androidx.arch.core:core-runtime:2.1.0' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.profileinstaller:profileinstaller:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.startup:startup-runtime:1.0.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.1.0',
[STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui-text:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.core:core:1.5.0' (releaseRuntimePublication) --> 'androidx.versionedparcelable:versionedparcelable:1.1.1' (runtime) --> 'androidx.annotation:annotation:1.1.0',
[STDERR]            Dependency path 'espresso-server-emulator-5554:app:unspecified' --> 'androidx.compose.ui:ui-test:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.compose.ui:ui:1.0.5' (releaseVariantReleaseRuntimePublication) --> 'androidx.profileinstaller:profileinstaller:1.0.4' (releaseVariantReleaseRuntimePublication) --> 'androidx.startup:startup-runtime:1.0.0' (releaseRuntimePublication) --> 'androidx.tracing:tracing:1.0.0' (releaseRuntimePublication) --> 'androidx.annotation:annotation:1.1.0',

```

**Comment by KazuCocoa** [comment]
Did you try https://github.com/appium/appium-espresso-driver/pull/787 in my previous comment as well?

**Comment by activesince93** [comment]
Yes, I tried that as well, getting the same error. I was wondering, is it related to only `androidx.annotation:annotation:1.2.0` dependency or all the dependencies mentioned in the log.

**Comment by JuanCarlos-Arceredillo** [comment]
The only way that we have found to avoid this situation is to change the gradle file to mark the annotation dependency as forced. But it would require a change in the gradle file and I'm not 100% percent sure that it was an acceptable change.

**Comment by KazuCocoa** [comment]
Maybe, ideally all dependencies should have `exclude("androidx.annotation", "annotation")` like https://github.com/appium/appium-espresso-driver/pull/787 (this was test package for compose tho). I assume `androidx.compose.ui:ui` also should have it... Then, the annotation version should be set as one dependency.

**Comment by activesince93** [comment]
I no longer see this error when I add this code in `espresso-server/app/build.gradle.kts`.  
```
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "androidx.annotation"
            && !requested.name.contains("annotation")
        ) {
            useVersion("1.1.0")
        }
    }
}
```

**Comment by KazuCocoa** [comment]
Thank you. I've updated https://github.com/appium/appium-espresso-driver/pull/787 .

**Comment by KazuCocoa** [comment]
`2.5.0` has the `annotationVersion` capability as `toolsVersions`. Then, it forcefully set the version as https://github.com/appium/appium-espresso-driver/issues/781#issuecomment-1149642991

**Comment by KazuCocoa** [comment]
Please try out espresso driver 2.5.0 and `annotationVersion` caps as `toolsVersions` to specify the annotation version as it.
