### ISSUE TITLE
Getting error 500 after switching to compose view on findelement/getpagesource

### ISSUE THREAD

**Issue by rockstarrocks2020** [appium/appium-espresso-driver#786]
Getting error while trying to findelement or trying to get page source.
after switching to compose
[debug] [ADB] Waiting up to 10000000000000ms for activity matching pkg: 'in.company.activity' and activity: 'in.selectActivity' to be focused
[debug] [ADB] Possible activities, to be checked: 'in.SelectActivity', 'in.SelectActivity'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys window displays'
[debug] [ADB] Found package: 'in.company' and fully qualified activity name : 'in.SelectActivity'
[debug] [EspressoDriver@91fb (53b128e1)] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8301/session/4713cc38-d140-414f-8e7c-3e793f46daf9/appium/device/info] with no body
[debug] [EspressoDriver@91fb (53b128e1)] Got response with status 200: {"id":"80efcb4e-44db-4901-8361-17e0e597d7a2","sessionId":"4713cc38-d140-414f-8e7c-3e793f46daf9","value":{"realDisplaySize":"1080x2340","apiVersion":"30","carrierName":"IND airtel","platformVersion":"11","timeZone":"Asia/Kolkata","model":"M2004J19C","locale":"en","brand":"Redmi","androidId":"242ad368615895c8","manufacturer":"Xiaomi","displayDensity":440}}
[AppiumDriver@f187] New EspressoDriver session created successfully, session 53b128e1-7d30-4709-acac-9ef4895c4cba added to master session list
[debug] [AppiumDriver@f187] Event 'newSessionStarted' logged
   at 1654250608316 (15:33:28 GMT+0530 (India Standard Time).1654250608316 (15:33:28 GMT+0530 (India Standard Time))
[debug] [EspressoDriver@91fb (53b128e1)] Cached the protocol value 'W3C' for the new session 53b128e1-7d30-4709-acac-9ef4895c4cba
[debug] [EspressoDriver@91fb (53b128e1)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"android","app":"/Users/user/Downloads/onboarding_test_tag.apk","appActivity":"in.SelectActivity","appPackage":"in.company","appWaitActivity":"in.SelectActivity","appWaitDuration":10000000000000,"automationName":"Espresso","espressoBuildConfig":"{\n  \"toolsVersions\": {\n    \"composeVersion\": \"1.2.0-beta01\"\n,    \"compileSdk\": \"32\"\n,    \"kotlin\": \"1.6.21\"\n  },\n  \"additionalAndroidTestDependencies\": [\"androidx.compose.ui:ui:1.2.0-beta01\"]\n}","espressoServerLaunchTimeout":1000000000,"forceEspressoRebuild":true,"noSign":false,"showGradleLog":true,"autoGrantPermissions":true}}
[HTTP] <-- POST /session 200 27305 ms - 800
[HTTP] 
[HTTP] --> POST /session/53b128e1-7d30-4709-acac-9ef4895c4cba/appium/settings
[HTTP] {"settings":{"driver":"compose"}}
[debug] [EspressoDriver@91fb (53b128e1)] Calling AppiumDriver.updateSettings() with args: [{"driver":"compose"},"53b128e1-7d30-4709-acac-9ef4895c4cba"]
[debug] [EspressoDriver@91fb (53b128e1)] Matched '/appium/settings' to command name 'updateSettings'
[debug] [EspressoDriver@91fb (53b128e1)] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8301/session/4713cc38-d140-414f-8e7c-3e793f46daf9/appium/settings] with body: {"settings":{"driver":"compose"}}
[debug] [EspressoDriver@91fb (53b128e1)] Got response with status 200: {"id":"40673ac5-8026-43ef-8825-4560a7a10edb","sessionId":"4713cc38-d140-414f-8e7c-3e793f46daf9","value":null}
[debug] [EspressoDriver@91fb (53b128e1)] Responding to client with driver.updateSettings() result: null
[HTTP] <-- POST /session/53b128e1-7d30-4709-acac-9ef4895c4cba/appium/settings 200 21 ms - 14
[HTTP] 
[HTTP] --> GET /session/53b128e1-7d30-4709-acac-9ef4895c4cba/source
[HTTP] {}
[EspressoDriver@91fb (53b128e1)] Driver proxy active, passing request on via HTTP proxy
[debug] [EspressoDriver@91fb (53b128e1)] Matched '/session/53b128e1-7d30-4709-acac-9ef4895c4cba/source' to command name 'getPageSource'
[debug] [EspressoDriver@91fb (53b128e1)] Proxying [GET /session/53b128e1-7d30-4709-acac-9ef4895c4cba/source] to [GET http://127.0.0.1:8301/session/4713cc38-d140-414f-8e7c-3e793f46daf9/source] with no body
[EspressoDriver@91fb (53b128e1)] Got response with status 500: {"id":"442565f1-2359-431f-8b5b-e3f8d45d09af","sessionId":"4713cc38-d140-414f-8e7c-3e793f46daf9","value":{"error":"unknown error","message":"java.lang.NoSuchMethodError: No virtual method replace(ILjava/lang/Object;)Ljava/lang/Object; in class Landroidx/collection/SparseArrayCompat; or its super classes (declaration of 'androidx.collection.SparseArrayCompat' appears in /data/app/~~H8OO8PDsRx_4yvArZEUOcQ==/io.appium.espressoserver.test-wkTCLlHYgznplPpdVhQZng==/base.apk)","stacktrace":"java.lang.NoSuchMethodError: No virtual method replace(ILjava/lang/Object;)Ljava/lang/Object; in class Landroidx/collection/SparseArrayCompat; or its super classes (declaration of 'androidx.collection.SparseArrayCompat' appears in /data/app/~~H8OO8PDsRx_4yvArZEUOcQ==/io.appium.espressoserver.test-wkTCLlHYgznplPpdVhQZng==/base.apk)\n\tat androidx.navigation.NavController.setGraph(NavController.kt:1077)\n\tat androidx.navigation.NavController.setGraph(NavController.kt:99)\n\tat androidx.navigation.compose.NavHostKt.NavHost(NavHos...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[HTTP] <-- GET /session/53b128e1-7d30-4709-acac-9ef4895c4cba/source 500 49 ms - 4924
[HTTP] 
[EspressoDriver@d7c8 (a9025436)] Shutting down because we waited 60 seconds for a command
[AppiumDriver@f187] Ending session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[AppiumDriver@f187] Removing session 'a9025436-a09e-442c-a882-e19110396333' from our master session list
[debug] [EspressoDriver@d7c8 (a9025436)] Deleting espresso session
[debug] [EspressoDriver@d7c8 (a9025436)] Deleting Espresso server session
[EspressoDriver@d7c8 (a9025436)] Did not get confirmation Espresso deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to Espresso server because the instrumentation process has crashed. Check the Appium server log and the logcat output for more details
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell am force-stop in.company'
[debug] [EspressoDriver@91fb (53b128e1)] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [EspressoDriver@91fb (53b128e1)] INSTRUMENTATION_CODE: 0
[debug] [Logcat] Stopping logcat capture
[EspressoDriver@d7c8 (a9025436)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [ADB] Removing forwarded port socket connection: 8300 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 forward --remove tcp:8300'
[EspressoDriver@91fb (53b128e1)] Instrumentation process exited with code 0 from signal null
[EspressoDriver@91fb (53b128e1)] Shutting down because we waited 60 seconds for a command
[AppiumDriver@f187] Ending session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[AppiumDriver@f187] Removing session '53b128e1-7d30-4709-acac-9ef4895c4cba' from our master session list
[debug] [EspressoDriver@91fb (53b128e1)] Deleting espresso session
[debug] [EspressoDriver@91fb (53b128e1)] Deleting Espresso server session
[EspressoDriver@91fb (53b128e1)] Did not get confirmation Espresso deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to Espresso server because the instrumentation process has crashed. Check the Appium server log and the logcat output for more details
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell am force-stop in.company'
[debug] [Logcat] Stopping logcat capture
[EspressoDriver@91fb (53b128e1)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [ADB] Removing forwarded port socket connection: 8301 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 forward --remove tcp:8301'

**Comment by rajdeepv** [comment]
Looks like dependencies conflict between the app under test and the espresso server. Please synchronize dependencies using this capability https://github.com/appium/appium-espresso-driver#espresso-build-config
an example is:
```
espressoBuildConfig: '{"additionalAndroidTestDependencies": ["androidx.lifecycle:lifecycle-extensions:2.2.0", "androidx.activity:activity:1.3.1",  "androidx.fragment:fragment:1.2.0"]}'
  }
```

**Comment by rockstarrocks2020** [comment]
Yes @rajdeepv seems the same issue but if one dependency is resolved the other is getting added. will request dev to add dependencies to add them in the instrumentation only.Can you suggest anything on that for dev team to add as dependencies.

**Comment by rajdeepv** [comment]
as per the above error, my guess is it is something to do with the version of `navigation-compose`, but the best thing to do is compare the Gradle dependencies graph of the espresso server with your app to figure out the difference.

**Comment by rockstarrocks2020** [comment]
ok thanks @rajdeepv.the issue added here is resolved
