### ISSUE TITLE
Getting Instrumentation Issue with 500 response

### ISSUE THREAD

**Issue by rockstarrocks2020** [appium/appium-espresso-driver#788]
Hi Team

Getting below issue , is there any way we can add signature from our end without depending on dev

[debug] [ADB] Uninstalling io.appium.espressoserver.test
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is installed
[debug] [ADB] Running '/Users/users/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell am force-stop io.appium.espressoserver.test'
[debug] [ADB] Running '/Users/users/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 uninstall io.appium.espressoserver.test'
[debug] [ADB] 'adb uninstall io.appium.espressoserver.test' command output: Success
[ADB] io.appium.espressoserver.test was successfully uninstalled
[EspressoDriver@2675 (812bfc75)] Uninstalled the obsolete Espresso server package from the device under test
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/users/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is not installed
[debug] [ADB] App '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_2.4.0_in.company.apk' is not installed
[EspressoDriver@2675 (812bfc75)] Installing Espresso Test Server apk from the target device (path: '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_2.4.0_in.company.apk')
[ADB] The application at '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_2.4.0_in.company.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 install /var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_2.4.0_in.company.apk'
[ADB] The installation of 'io.appium.espressoserver.test_2.4.0_in.company.apk' took 1719ms
[debug] [ADB] Install command stdout: Serving...
[debug] [ADB] Performing Incremental Install
[debug] [ADB] 
[debug] [ADB] Exception occurred while executing 'install-incremental':
[debug] [ADB] java.lang.IllegalArgumentException: Incremental i...
[debug] [ADB] 
   at android.os.Binder.execTransactInternal(Binder.java:1159 undefined)
[debug] [ADB] 
   at android.os.Binder.execTransact(Binder.java:1123 undefined)
[debug] [ADB] Performing Streamed Install
[debug] [ADB] Success
[EspressoDriver@2675 (812bfc75)] Installed Espresso Test Server apk '/var/folders/s6/_2yh3tdj01j8dv99gt59dtyw0000gn/T/io.appium.espressoserver.test_2.4.0_in.company.apk' (pkg: 'io.appium.espressoserver.test')
[ADB] Adding packages ["io.appium.settings","io.appium.espressoserver.test"] to Doze whitelist
[debug] [ADB] Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.espressoserver.test",";"]]
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.espressoserver.test ;'
[debug] [EspressoDriver@2675 (812bfc75)] Performing cleanup of automation leftovers
[debug] [EspressoDriver@2675 (812bfc75)] No obsolete sessions have been detected (socket hang up)
[EspressoDriver@2675 (812bfc75)] Starting Espresso Server v2.4.0 with cmd: adb shell am instrument -w -e debug false -e disableAnalytics true io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","0a3e9cb90409","shell","am","instrument","-w","-e","debug",false,"-e","disableAnalytics",true,"io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[EspressoDriver@2675 (812bfc75)] Waiting up to 1000000000ms for Espresso server to be online
[debug] [EspressoDriver@2675 (812bfc75)] Matched '/status' to command name 'getStatus'
[debug] [EspressoDriver@2675 (812bfc75)] Proxying [GET /status] to [GET http://127.0.0.1:8300/status] with no body
[EspressoDriver@2675 (812bfc75)] socket hang up
[debug] [EspressoDriver@2675 (812bfc75)] Matched '/status' to command name 'getStatus'
[debug] [EspressoDriver@2675 (812bfc75)] Proxying [GET /status] to [GET http://127.0.0.1:8300/status] with no body
[EspressoDriver@2675 (812bfc75)] socket hang up
[debug] [EspressoDriver@2675 (812bfc75)] [Instrumentation] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=6930, uid=6930 not allowed because package io.appium.espressoserver.test does not have a signature matching the target in.company
[debug] [EspressoDriver@2675 (812bfc75)] INSTRUMENTATION_STATUS: id=ActivityManagerService
[debug] [EspressoDriver@2675 (812bfc75)] INSTRUMENTATION_STATUS_CODE: -1
[debug] [EspressoDriver@2675 (812bfc75)] [Instrumentation] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=6930, uid=6930 not allowed because package io.appium.espressoserver.test does not have a signature matching the target in.company
[debug] [EspressoDriver@2675 (812bfc75)] [Instrumentation]
   at android.os.Parcel.createExceptionOrNull(Parcel.java:2376 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.os.Parcel.createException(Parcel.java:2360 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.os.Parcel.readException(Parcel.java:2343 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.os.Parcel.readException(Parcel.java:2285 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:6371 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.commands.am.Instrument.run(Instrument.java:517 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] [Instrumentation]
   at com.android.commands.am.Am.runInstrument(Am.java:202 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.commands.am.Am.onRun(Am.java:80 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.internal.os.BaseCommand.run(BaseCommand.java:60 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.commands.am.Am.main(Am.java:50 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:427 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] Caused by: android.os.RemoteException: Remote stack trace:
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:17593 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2783 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3002 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.os.Binder.execTransactInternal(Binder.java:1154 undefined)
[debug] [EspressoDriver@2675 (812bfc75)] 
   at android.os.Binder.execTransact(Binder.java:1123 undefined)
[EspressoDriver@2675 (812bfc75)] Instrumentation process exited with code 1 from signal null
[EspressoDriver@2675 (812bfc75)] Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details
[debug] [EspressoDriver@2675 (812bfc75)] Deleting espresso session
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell am force-stop in.company'
[debug] [Logcat] Stopping logcat capture
[debug] [Logcat] Logcat already stopped
[EspressoDriver@2675 (812bfc75)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [ADB] Removing forwarded port socket connection: 8300 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 0a3e9cb90409 forward --remove tcp:8300'
[debug] [AppiumDriver@3fae] Event 'newSessionStarted' logged
   at 1654596872175 (15:44:32 GMT+0530 (India Standard Time).1654596872175 (15:44:32 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@3fae] Encountered internal error running command: A new session could not be created. Details: Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [AppiumDriver@3fae] Error: Espresso server process has been unexpectedly terminated. Check the Appium server log and the logcat output for more details. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [AppiumDriver@3fae]     at Object.errorAndThrow (/Users/user
/.appium/node_modules/appium-espresso-driver/node_modules/@appium/support/lib/logging.js:111:35)
[debug] [AppiumDriver@3fae]    
   at condFn .condFn (/Users/user/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:285:20 undefined)
[debug] [AppiumDriver@3fae]    
   at spin .spin (/Users/user/.appium/node_modules/appium-espresso-driver/node_modules/asyncbox/lib/asyncbox.js:138:26 undefined)
[debug] [AppiumDriver@3fae]    
   at spin .spin (/Users/user/.appium/node_modules/appium-espresso-driver/node_modules/asyncbox/lib/asyncbox.js:148:20 undefined)
[debug] [AppiumDriver@3fae]    
   at spin .spin (/Users/user/.appium/node_modules/appium-espresso-driver/node_modules/asyncbox/lib/asyncbox.js:148:14 undefined)
[debug] [AppiumDriver@3fae]    
   at waitForCondition .waitForCondition (/Users/user/.appium/node_modules/appium-espresso-driver/node_modules/asyncbox/lib/asyncbox.js:155:10 undefined)
[debug] [AppiumDriver@3fae]    
   at EspressoRunner.startSession (/Users/user/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:279:7 undefined)
[debug] [AppiumDriver@3fae]    
   at EspressoDriver.startEspressoSession (/Users/user/.appium/node_modules/appium-espresso-driver/lib/driver.js:443:5 undefined)
[debug] [AppiumDriver@3fae]    
   at EspressoDriver.createSession (/Users/user/.appium/node_modules/appium-espresso-driver/lib/driver.js:224:7 undefined)
[debug] [AppiumDriver@3fae]    
   at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:334:35 undefined)
[HTTP] <-- POST /session 500 71562 ms - 1923
[HTTP]

**Comment by KazuCocoa** [comment]
> [debug] [EspressoDriver@2675 (812bfc75)] [Instrumentation] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=6930, uid=6930 not allowed because package io.appium.espressoserver.test does not have a signature matching the target in.company

Probably the espresso server and the app under test did not have the same signature. Please make sure they have the same sign.
https://github.com/appium/appium-espresso-driver#app-signing is the capabilities.
