### ISSUE TITLE
StartActivity does not support IntentOptions

### ISSUE THREAD

**Issue by msaravana123** [appium/appium-espresso-driver#802]
We are migrating UiAutomator2 scripts to Espresso.

I am facing issue with startingActivity with intentOptions (as Intent Action and Intent Arguments are not supported)

UiAutomator2:
``` 
Activity activity = new Activity(appPackage, appActivity);
activity.setIntentAction(intentAction);
activity.setOptionalIntentArguments(intentArguments);
driver.startActivity(activity);
```
Espresso
```
Activity activity = new Activity(appPackage, appActivity);
activity.setOptionalIntentArguments(intentArguments); //IntentOptions as JSON String
driver.startActivity(activity);
```

But only appPackage and appActivity are sent to Espresso server but intent options are not sent even though espresso startactivity supports IntentOptions.

The following call works and starts the correct activity with right data setting.
http://localhost:8300/session/{sessionId}/appium/device/start_activity

```
{
    "appPackage": "XXXXXX",
    "appActivity": "XXXXXXXXX",
    "optionalIntentArguments": {
        "flags": "ACTIVITY_NEW_TASK",
        "action": "XXXXXXXX",
        "className": "XXXXX",
        "es": {
            "username": "pilot1",
            "env": "Test",
            "featureFlags": "XXXXXXXXX",
            "env1": "XXXXX",
            "env2": "XXXXXXX"
        }
    }
}
```

**Comment by msaravana123** [comment]
Raised a PR - https://github.com/appium/appium-espresso-driver/pull/803. Please review.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-espresso-driver/pull/803#issuecomment-1197730349
