### ISSUE TITLE
Mobile:swipe command not working for compose element

### ISSUE THREAD

**Issue by jasodhara** [appium/appium-espresso-driver#807]
- Able to identify the compose element using 'findelement'which is scrollable.
- Fetching the element id and storing in a hashmap
- Executing the 'mobile:swipe' command
- But the element id changes once 'mobile:swipe' command is executed and is throwing staleelementreference exception.
- Is there a way to tell the driver to use previous session id which was used to fetch the scrolling element or ensure that session id remains the same as previous command.Because the element id is becoming stale once the session id is changed for next execute command.
Will it not work for compose element?

Client code:
HashMap<String, String> swipeObject = new HashMap<String, String>();
 RemoteWebElement scrollbar=(RemoteWebElement) driver.findElement(By.xpath("//ComposeNode/VerticalScrollAxisRange"));
swipeObject.put("element", scrollbar.getId());
swipeObject.put("direction", "up");
driver.executeScript("mobile: swipe",swipeObject);

Appium logs:
[HTTP] --> POST /wd/hub/session/712cb179-03fa-4783-abda-a4b384b07c2f/element
[HTTP] {"using":"xpath","value":"//ComposeNode/VerticalScrollAxisRange"}
[EspressoDriver@5d54 (712cb179)] Driver proxy active, passing request on via HTTP proxy
[debug] [EspressoDriver@5d54 (712cb179)] Matched '/wd/hub/session/712cb179-03fa-4783-abda-a4b384b07c2f/element' to command name 'findElement'
[debug] [EspressoDriver@5d54 (712cb179)] Proxying [POST /wd/hub/session/712cb179-03fa-4783-abda-a4b384b07c2f/element] to [POST http://127.0.0.1:8300/session/a8599ba6-464f-434a-8046-95e576f36c46/element] with body: {"using":"xpath","value":"//ComposeNode/VerticalScrollAxisRange"}
[debug] [EspressoDriver@5d54 (712cb179)] Got response with status 200: {"id":"fa3b95b9-6fb0-4078-9d60-caca3d3f31b0","sessionId":"a8599ba6-464f-434a-8046-95e576f36c46","value":{"ELEMENT":"9b86459c-61ab-4dae-86a5-7832ebf14342"}}
[EspressoDriver@5d54 (712cb179)] **Replacing sessionId a8599ba6-464f-434a-8046-95e576f36c46 with 712cb179-03fa-4783-abda-a4b384b07c2f**
[HTTP] <-- POST /wd/hub/session/712cb179-03fa-4783-abda-a4b384b07c2f/element 200 180 ms - 232
[HTTP]
[HTTP] --> POST /wd/hub/session/712cb179-03fa-4783-abda-a4b384b07c2f/execute/sync
[HTTP] {"script":"mobile: swipe","args":[{"element":"9b86459c-61ab-4dae-86a5-7832ebf14342","direction":"up"}]}
[debug] [EspressoDriver@5d54 (712cb179)] **Calling AppiumDriver.execute() with args: ["mobile: swipe",[{"element":"9b86459c-61ab-4dae-86a5-7832ebf14342","direction":"up"}],"712cb179-03fa-4783-abda-a4b384b07c2f"]**
[EspressoDriver@5d54 (712cb179)] Executing native command 'mobile: swipe'
[debug] [EspressoDriver@5d54 (712cb179)] Proxying [POST /appium/execute_mobile/9b86459c-61ab-4dae-86a5-7832ebf14342/swipe] to [POST http://127.0.0.1:8300/session/a8599ba6-464f-434a-8046-95e576f36c46/appium/execute_mobile/9b86459c-61ab-4dae-86a5-7832ebf14342/swipe] with body: {"direction":"up","element":"9b86459c-61ab-4dae-86a5-7832ebf14342"}
[EspressoDriver@5d54 (712cb179)] **Got response with status 500: {"id":"cfd42bc1-b51a-4c3a-98ca-faea0fcc388b","sessionId":"a8599ba6-464f-434a-8046-95e576f36c46","value":{"error":"unknown error","message":"java.util.NoSuchElementException: The element identified by '9b86459c-61ab-4dae-86a5-7832ebf14342' does not exist in the cache or has expired. Try to find it again","stacktrace":"java.util.NoSuchElementException: The element identified by '9b86459c-61ab-4dae-86a5-7832ebf14342' does not exist in the cache or has expired. Try to find it again\n\tat** io.appium.espressoserver.lib.model.EspressoElement$Companion.getViewById(Element.kt:113)\n\tat io.appium.espressoserver.lib.model.EspressoElement$Companion.getViewById$default(Element.kt:110)\n\tat io.appium.espressoserver.lib.model.EspressoElement$Companion.getViewInteractionById(Element.kt:68)\n\tat io.appium.espressoserver.lib.handlers.MobileSwipe.handleInternal(MobileSwipe.kt:36)\n\tat io.appium.espressoserver.lib.handlers.MobileSwipe.handleInternal(MobileSwipe.kt:31)\n\tat io.appium.espressoserver.lib.handlers.RequestHand...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [EspressoDriver@5d54 (712cb179)] Encountered internal error running command: An unknown server-side error occurred while processing the command. Original error: java.util.NoSuchElementException: The element identified by '9b86459c-61ab-4dae-86a5-7832ebf14342' does not exist in the cache or has expired. Try to find it again
[debug] [EspressoDriver@5d54 (712cb179)] java.util.NoSuchElementException: The element identified by '9b86459c-61ab-4dae-86a5-7832ebf14342' does not exist in the cache or has expired. Try to find it again
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.model.EspressoElement$Companion.getViewById(Element.kt:113)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.model.EspressoElement$Companion.getViewById$default(Element.kt:110)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.model.EspressoElement$Companion.getViewInteractionById(Element.kt:68)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.handlers.MobileSwipe.handleInternal(MobileSwipe.kt:36)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.handlers.MobileSwipe.handleInternal(MobileSwipe.kt:31)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handle(RequestHandler.kt:57)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.handlers.MobileSwipe.handle(MobileSwipe.kt:31)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.handlers.MobileSwipe.handle(MobileSwipe.kt:31)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.http.Router.route(Router.kt:229)
[debug] [EspressoDriver@5d54 (712cb179)]        at io.appium.espressoserver.lib.http.Server.serve(Server.kt:51)
[debug] [EspressoDriver@5d54 (712cb179)]        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
[debug] [EspressoDriver@5d54 (712cb179)]        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
[debug] [EspressoDriver@5d54 (712cb179)]        at java.lang.Thread.run(Thread.java:923)
[debug] [EspressoDriver@5d54 (712cb179)]
[HTTP] <-- POST /wd/hub/session/712cb179-03fa-4783-abda-a4b384b07c2f/execute/sync 500 167 ms - 1541
[HTTP]

**Comment by mykola-mokhnach** [comment]
This is expected. The tutorial explicitly says that Compose mode only supports a limited set of APIs and the above mobile extension is not in that set.

**Comment by jasodhara** [comment]
Thanks for confirmation.

**Comment by mykola-mokhnach** [comment]
You could create a PR and add the needed functionality. I assume Compose API should allow to perform swipes

**Comment by jasodhara** [comment]
okay @mykola-mokhnach 
I will create a pull request and add the required code in below file:
appium-espresso-driver/tree/master/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileSwipe.kt

In case I need help can I reach out to someone who has experience with compose?

**Comment by jasodhara** [comment]
@mykola-mokhnach 
Hi,

I have added required code to support Mobile Swipe for compose element.But when I am trying to push the code in the branch created,it is giving below error.Is there any specific access required.
Event Log:
```
2:18 PM	Push failed
				remote: Permission to appium/appium-espresso-driver.git denied to jasodhara.
				unable to access 'https://github.com/appium/appium-espresso-driver.git/': The requested URL returned error: 403
				Show details in console
```
Console:
```
14:18:18.282: [appium-espresso-driver] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/add-composesupport-swipe:add-composesupport-swipe --set-upstream
remote: Permission to appium/appium-espresso-driver.git denied to jasodhara.
fatal: unable to access 'https://github.com/appium/appium-espresso-driver.git/': The requested URL returned error: 403
```

**Comment by mykola-mokhnach** [comment]
Please create your own fork of the original repository and make a PR from there: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
