### ISSUE TITLE
Type Error: helpers.installAppremotely

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-espresso-driver#81]
@dpgraham i was trying the latest 1.8.0-beta3 with espresso driver and it failed to install the application 

https://gist.github.com/saikrishna321/9ae97f8d74281f03fa132f979c3806c9#file-gistfile1-txt-L196

This the line https://github.com/appium/appium-espresso-driver/blob/master/lib/driver.js#L306 the log is showing error. But i don't see the installRemoteApk method.

Can you please help on this, would want to understand and fix

**Comment by mykola-mokhnach** [comment]
It's fixed by https://github.com/appium/appium-espresso-driver/pull/80. Needs to be tagged though

**Comment by saikrishna321** [comment]
@mykola-mokhnach i deleted the appium-espresso driver from node_modules and cloned this repo and did a npm install to have the latest.

i bumped into this issue 

https://gist.github.com/saikrishna321/9a352387c65e4c9adef65df3f245e7b5

Else can you please tag the build so that i can test espresso driver

**Comment by dpgraham** [comment]
@saikrishna321 Just published beta.8; FYI, the Espresso Driver is still in a very early beta phase.

**Comment by saikrishna321** [comment]
@dpgraham Thanks that issue has been resolved :)
