### ISSUE TITLE
Error performing getting view in application on view is a root view

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-espresso-driver#82]
When i try to get the pageSource or screenshot i get the below error 

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 500 - "{\"message\":\"Internal error has occurred\",\"reason\":\"Error performing \\u0027getting view in application\\u0027 on view \\u0027is a root view.\\u0027.\"}" (WARNING: The server did not provide any stacktrace information)

Server logs : https://gist.github.com/saikrishna321/537cb5260b4a2630e35c3813f48388d6
Adb logs: https://gist.github.com/saikrishna321/e27a342eff558f30c4537db660560404
Running from appium-master with expresso driver 1.0.0beta8

**Comment by jlipps** [comment]
I've also run into this error, with a react native app.

**Comment by saikrishna321** [comment]
Its the same, i'm also running with RN app. Let me try with Native app n check if the same happens

**Comment by saikrishna321** [comment]
Same with Native application as well

**Comment by dpgraham** [comment]
Closing this. I'm pretty sure it's fixed, will open again if it's not.
