### ISSUE TITLE
XPATH return only first found element

### ISSUE THREAD

**Issue by bronik** [appium/appium-espresso-driver#829]
**appium version:** 1.22.3
**espresso driver version:** 2.13.1 
**fyi:** issue doesn't reproduce on espresso-driver version 2.9.0

I found weird behaviour while searching elements. Xpath returns only 1st found element.
Sorry but I can't provide my app source, so i'll try to explain behaviour with 'abstract application'

For example, we have few elements with some resource-ids on the screen:
elementA with id = imgAvatar
elementB with id = imgAvatar
elementC with id = userAvatar
elementD with id = userAvatar

**Actual results:**
1) searching by xpath
**xpath for element search:**
//*[@resource-id="app:id/imgAvatar" or @resource-id="app:id/userAvatar"]
**search result:**
elementA

2) searching by xpath
**xpath for element search:**
(//*[@resource-id="app:id/imgAvatar" or @resource-id="app:id/userAvatar"])[2]
**search result:**
elementB

3) searching by ID
**searchId:**
imgAvatar
**search result:**
elementA
elementB

As you see, trouble appears only when searching with xpath for several elements.. 

I have no logs for now, 'cause I've already downgrade appium version to 2.9.0 and it works fine. If you need some additional info - please, let me know. I'll add it on the weekend

**Comment by mykola-mokhnach** [comment]
Could you please confirm https://github.com/appium/appium-espresso-driver/pull/830 works for you?

**Comment by bronik** [comment]
thanks for your fast answer
tested. works fine with your fixes, thanks a lot!
