### ISSUE TITLE
NoSuchElementException while taking screenshot of any compose element

### ISSUE THREAD

**Issue by bronik** [appium/appium-espresso-driver#840]
Hi everyone

As you can read in the title, I'm facing NoSuchElementException when trying to get screenshot of ANY compose element

`An unknown server-side error occurred while processing the command. Original error: java.util.NoSuchElementException: The element identified by 'c89c6e99-258e-48b8-9410-617fb25d0892' does not exist in the cache or has expired. Try to find it again`

it works properly when i'm getting screenshot of espresso element (with espresso driver)

i've been trying find element with different locators and strategies (xpath, tag)
i'm getting screenshot as below:
`**linkToMyMobileElementObject**.getScreenshotAs(OutputType.FILE)`

element is actually found and it's doesn't recreates on the screen
and yes, I can interact with this element

i'm using:
appium v.1.22.3
appium-espresso-driver v2.13.8

is that my local trouble or screenshots doesn't work with compose elements at all?

**Comment by bronik** [comment]
anyone?) i'm stuck there :)

**Comment by KazuCocoa** [comment]
Latest driver version with Appium 2.0 would help
