### ISSUE TITLE
Issue that does not execute Gradle and cannot load driver

### ISSUE THREAD

**Issue by qa-inho-song** [appium/appium-espresso-driver#845]
Hi, I'm building a test automation environment, but I can't run Gradle and I can't run it from the driver. Please help me.

source
-------------------------------------------------------------------------------------------
# import the necessary libraries
from appium import webdriver

# desired capabilities for the Appium driver
desired_caps = {
    'platformName': 'Android',
    'platformVersion': '13.0',
    'deviceName': 'emulator',
    'appPackage': 'com.beta',
    'appActivity': 'com.SplashActivity',
    'automationName': 'espresso',
    'autoGrantPermissions': 'true'
}

# create the Appium driver using the desired capabilities
driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_caps)

# test steps
def test_login():
    # Check that the element is displayed
    el = driver.find_element_by_id("00000000-0000-028b-3b9a-ca2a00000016")
    assert el.is_displayed()
    el.click()
    
    driver.quit()
-------------------------------------------------------------------------------------------

error
and_run.py:None (and_run.py)
and_run.py:16: in <module>
    driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_caps)
../../Library/Python/3.11/lib/python/site-packages/appium/webdriver/webdriver.py:230: in __init__
    super().__init__(
../../Library/Python/3.11/lib/python/site-packages/selenium/webdriver/remote/webdriver.py:288: in __init__
    self.start_session(capabilities, browser_profile)
../../Library/Python/3.11/lib/python/site-packages/appium/webdriver/webdriver.py:320: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
../../Library/Python/3.11/lib/python/site-packages/selenium/webdriver/remote/webdriver.py:444: in execute
    self.error_handler.check_response(response)
../../Library/Python/3.11/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py:249: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=com.android.beta app\:assembleAndroidTest')
E   Gradle error message:
E   
E   [STDOUT] > Task :app:processDebugMainManifest FAILED,
E   [STDOUT] 7 actionable tasks: 1 executed, 6 up-to-date,
E   [STDERR] ,
E   [STDERR] FAILURE: Build failed with an exception.,
E   [STDERR] ,
E   [STDERR] * What went wrong:,
E   [STDERR] Execution failed for task ':app:processDebugMainManifest'.,
E   [STDERR] > Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @21a58479,
E   [STDERR] ,
E   [STDERR] * Try:,
E   [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
E   [STDERR] ,
E   [STDERR] * Get more help at https://help.gradle.org,
E   [STDERR] ,
E   [STDERR] BUILD FAILED in 3s. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
E   Stacktrace:
E   Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=com.beta app\:assembleAndroidTest')
E   Gradle error message:
E   
E   [STDOUT] > Task :app:processDebugMainManifest FAILED,
E   [STDOUT] 7 actionable tasks: 1 executed, 6 up-to-date,
E   [STDERR] ,
E   [STDERR] FAILURE: Build failed with an exception.,
E   [STDERR] ,
E   [STDERR] * What went wrong:,
E   [STDERR] Execution failed for task ':app:processDebugMainManifest'.,
E   [STDERR] > Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @21a58479,
E   [STDERR] ,
E   [STDERR] * Try:,
E   [STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
E   [STDERR] ,
E   [STDERR] * Get more help at https://help.gradle.org,
E   [STDERR] ,
E   [STDERR] BUILD FAILED in 3s. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
E       at Object.errorAndThrow (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
E       at ServerBuilder.runBuildProcess (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:188:11)
E       at ServerBuilder.build (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:69:5)
E       at EspressoRunner.buildNewModServer (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:187:5)
E       at EspressoRunner.installTestApk (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:145:7)
E       at EspressoDriver.initAUT (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:432:7)
E       at EspressoDriver.startEspressoSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:296:5)
E       at EspressoDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/driver.js:188:7)
E       at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:35)

thanks.

**Comment by KazuCocoa** [comment]
Please try with latest espresso driver with Appium 2.0

**Comment by qa-inho-song** [comment]
@KazuCocoa Hi, thanks to you, I knew the existence of 2.0 and installed it. Thank you.

**Comment by qa-inho-song** [comment]
@KazuCocoa I installed appium 2.0 and espresso, but it's reproducing the same thing.
What can I try?

**Comment by KazuCocoa** [comment]
You should figure out what dependencies you need to add for the Espresso build because the dependencies depends on the app under test.
https://github.com/appium/appium-espresso-driver#espresso-build-config

**Comment by qa-inho-song** [comment]
@KazuCocoa Thanks to you, I solved it.
