### ISSUE TITLE
Compose elements are not loaded after app starts with appium

### ISSUE THREAD

**Issue by bronik** [appium/appium-espresso-driver#869]
Hi everyone! 
I'm facing weird behaviour. Each time I start my app through appium inspector or java code - i didn't see some compose elements. Only after i press 'Refresh page sources'(in inspector) or driver.getPageSource() from code - every element displays correctly.

Is that normal behavior or I need add some additional dependencies to espressoBuildConfig?

fyi: when I launch app without appium - application displays each element immediately

**Comment by sravanmedarapu** [comment]
Invoking [mobile:waitForUIThread](https://github.com/sravanmedarapu/appium-espresso-driver/blob/d88b27140417e982b79ea483ad06d4286ef622d4/README.md#mobile-waitforuithread) should help.

**Comment by bronik** [comment]
you linked to another repo
real [espresso-driver](https://github.com/appium/appium-espresso-driver) has no **mobile:waitForUIThread** such command

`Only shell,execEmuConsoleCommand,performEditorAction,changePermissions,getPermissions,startScreenStreaming,stopScreenStreaming,swipe,scrollToPage,navigateTo,clickAction,deviceInfo,isToastVisible,openDrawer,closeDrawer,setDate,setTime,getDeviceTime,backdoor,flashElement,uiautomator,uiautomatorPageSource,webAtoms,getContexts,dismissAutofill,getNotifications,listSms,sensorSet,pushFile,pullFile,pullFolder,deleteFile,isAppInstalled,queryAppState,activateApp,removeApp,terminateApp,installApp,clearApp,startActivity,startService,stopService,broadcast,registerIdlingResources,unregisterIdlingResources,listIdlingResources,unlock,refreshGpsCache,startMediaProjectionRecording,isMediaProjectionRecordingRunning,stopMediaProjectionRecording commands are supported.`

**Comment by sravanmedarapu** [comment]
This API recently introduced in v[2.19.0](https://github.com/appium/appium-espresso-driver/releases/tag/v2.19.0), could please try on latest appium-espresso-driver.
