### ISSUE TITLE
Version 2.25.4 - Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by Baterka** [appium/appium-espresso-driver#905]
After upgrading from 2.25.3 to 2.25.4, I am getting error `Could not find or load main class org.gradle.wrapper.GradleWrapperMain` on Windows with latest appium.

**Comment by skrosoft** [comment]
I have the same error here with the version 2.25.5 🖐🏻

**Comment by KazuCocoa** [comment]
Should be ok with the latest. Thank you
