### ISSUE TITLE
"Error inserting manifest" during new session

### ISSUE THREAD

**Issue by jlipps** [appium/appium-espresso-driver#92]
See logs: https://gist.github.com/jlipps/c4fcca0c637c2a91d39882947cbcd4f9

Seems the test server's manifest can't be updated?

**Comment by mykola-mokhnach** [comment]
@jlipps Can you please make sure that appium-adb module is at the recent version? 
`at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:275:9)` currently there is a docstring at this line.

**Comment by jlipps** [comment]
```
~/c/a/appium-espresso-driver ❯❯❯ npm ls appium-adb       
appium-espresso-driver@1.0.0-beta.8 /Users/jlipps/Code/appium/appium-espresso-driver
├── appium-adb@6.3.1
└─┬ appium-android-driver@1.40.1
  ├── appium-adb@6.3.1  deduped
  └─┬ appium-android-bootstrap@2.10.1
    └─┬ appium-uiautomator@1.1.5
      └── appium-adb@5.6.1
```

looks like it's using the version from appium-uiautomator, which hasn't been updated after the major version bump

**Comment by mykola-mokhnach** [comment]
yep, uia driver should be at version 2

**Comment by mykola-mokhnach** [comment]
would you like me to create a PR?

**Comment by jlipps** [comment]
@mykola-mokhnach please, I'm not familiar right now with what breaking changes there might be

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-espresso-driver/pull/93

**Comment by vmaxim** [comment]
@mykola-mokhnach Something wrong with the published version:
```
c:\Users\xxx\AppData\Roaming\npm>npm install -g appium-adb

c:\Users\xxx\AppData\Roaming\npm\node_modules\appium-adb>find /N "insertManifest" .\lib\tools\android-manifest.js

---------- .\LIB\TOOLS\ANDROID-MANIFEST.JS
[254]manifestMethods.insertManifest = async function (manifest, srcApk, dstApk) {

c:\Users\xxx\AppData\Roaming\npm\node_modules\appium-adb>find /N "version" package.json

---------- PACKAGE.JSON
[146]  "version": "6.3.1"
```
