### ISSUE TITLE
Mobile Command "mobile:startLogsBroadcast" not available

### ISSUE THREAD

**Issue by olga999999** [appium/appium-espresso-driver#987]
An attempt to execute `driver.executeScript("mobile:startLogsBroadcast")` leads to `UnsupportedCommandException`, even though according to the documentation this command should be available in all Android drivers.

> org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "startLogsBroadcast". Only shell,execEmuConsoleCommand,performEditorAction,changePermissions,getPermissions,startScreenStreaming,stopScreenStreaming,swipe,scrollToPage,navigateTo,clickAction,deviceInfo,isToastVisible,openDrawer,closeDrawer,setDate,setTime,getDeviceTime,backdoor,flashElement,uiautomator,uiautomatorPageSource,webAtoms,getContexts,dismissAutofill,getNotifications,listSms,pushFile,pullFile,pullFolder,deleteFile,isAppInstalled,queryAppState,activateApp,removeApp,terminateApp,installApp,clearApp,backgroundApp,getCurrentActivity,getCurrentPackage,startActivity,startService,stopService,broadcast,registerIdlingResources,unregisterIdlingResources,listIdlingResources,waitForUIThread,lock,unlock,isLocked,refreshGpsCache,startMediaProjectionRecording,isMediaProjectionRecordingRunning,stopMediaProjectionRecording,getConnectivity,setConnectivity,toggleGps,isGpsEnables,pressKey,hideKeyboard,isKeyboardShown,getDisplayDensity,getSystemBars,fingerprint,sendSms,gsmCall,gsmSignal,gsmVoice,powerAc,powerCapacity,networkSpeed,sensorSet,getPerformanceData,getPerformanceDataTypes,statusBar,screenshots,setUiMode,getUiMode commands are supported.
> Build info: version: '4.17.0', revision: 'e52b1be057*'
> System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.3.1', java.version: '17.0.9'
> Driver info: io.appium.java_client.android.AndroidDriver
> Command: [f7988b9c-8c6a-4e80-a4e2-c38449428947, executeScript {args=[], script=mobile:startLogsBroadcast}]

Java client version: 9.1.0
Espresso driver: espresso@2.36.1
Appium: v2.5.1

**Comment by KazuCocoa** [comment]
Could you try https://github.com/appium/appium-espresso-driver/pull/988 out?
